// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package imaging

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureBitmapImage string = "rc(Windows.UI.Xaml.Media.Imaging.BitmapImage;{31af3271-e3b4-442d-a341-4c0226b2725b})"

type BitmapImage struct {
	ole.IUnknown
}

func NewBitmapImage() (*BitmapImage, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Media.Imaging.BitmapImage")
	if err != nil {
		return nil, err
	}
	return (*BitmapImage)(unsafe.Pointer(inspectable)), nil
}

func (impl *BitmapImage) SetUriSource(value *foundation.Uri) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBitmapImage))
	defer itf.Release()
	v := (*iBitmapImage)(unsafe.Pointer(itf))
	return v.SetUriSource(value)
}

func (impl *BitmapImage) SetDecodePixelWidth(value int32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBitmapImage))
	defer itf.Release()
	v := (*iBitmapImage)(unsafe.Pointer(itf))
	return v.SetDecodePixelWidth(value)
}

func (impl *BitmapImage) SetDecodePixelHeight(value int32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBitmapImage))
	defer itf.Release()
	v := (*iBitmapImage)(unsafe.Pointer(itf))
	return v.SetDecodePixelHeight(value)
}

const GUIDiBitmapImage string = "31af3271-e3b4-442d-a341-4c0226b2725b"
const SignatureiBitmapImage string = "{31af3271-e3b4-442d-a341-4c0226b2725b}"

type iBitmapImage struct {
	ole.IInspectable
}

type iBitmapImageVtbl struct {
	ole.IInspectableVtbl

	GetCreateOptions       uintptr
	SetCreateOptions       uintptr
	GetUriSource           uintptr
	SetUriSource           uintptr
	GetDecodePixelWidth    uintptr
	SetDecodePixelWidth    uintptr
	GetDecodePixelHeight   uintptr
	SetDecodePixelHeight   uintptr
	AddDownloadProgress    uintptr
	RemoveDownloadProgress uintptr
	AddImageOpened         uintptr
	RemoveImageOpened      uintptr
	AddImageFailed         uintptr
	RemoveImageFailed      uintptr
}

func (v *iBitmapImage) VTable() *iBitmapImageVtbl {
	return (*iBitmapImageVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBitmapImage) SetUriSource(value *foundation.Uri) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetUriSource,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in foundation.Uri
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iBitmapImage) SetDecodePixelWidth(value int32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDecodePixelWidth,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in int32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iBitmapImage) SetDecodePixelHeight(value int32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDecodePixelHeight,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in int32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiBitmapImage2 string = "1069c1b6-8c9b-4762-be3d-759f5698f2b3"
const SignatureiBitmapImage2 string = "{1069c1b6-8c9b-4762-be3d-759f5698f2b3}"

type iBitmapImage2 struct {
	ole.IInspectable
}

type iBitmapImage2Vtbl struct {
	ole.IInspectableVtbl

	GetDecodePixelType uintptr
	SetDecodePixelType uintptr
}

func (v *iBitmapImage2) VTable() *iBitmapImage2Vtbl {
	return (*iBitmapImage2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiBitmapImage3 string = "f1de6f26-3c73-453f-a7ba-9b85c18b3733"
const SignatureiBitmapImage3 string = "{f1de6f26-3c73-453f-a7ba-9b85c18b3733}"

type iBitmapImage3 struct {
	ole.IInspectable
}

type iBitmapImage3Vtbl struct {
	ole.IInspectableVtbl

	GetIsAnimatedBitmap uintptr
	GetIsPlaying        uintptr
	GetAutoPlay         uintptr
	SetAutoPlay         uintptr
	Play                uintptr
	Stop                uintptr
}

func (v *iBitmapImage3) VTable() *iBitmapImage3Vtbl {
	return (*iBitmapImage3Vtbl)(unsafe.Pointer(v.RawVTable))
}
