// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ui

const SignatureColor string = "struct(Windows.UI.Color;u1;u1;u1;u1)"

type Color struct {
	A uint8

	R uint8

	G uint8

	B uint8
}
