// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package primitives

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
)

const SignatureButtonBase string = "rc(Windows.UI.Xaml.Controls.Primitives.ButtonBase;{fa002c1a-494e-46cf-91d4-e14a8d798674})"

type ButtonBase struct {
	ole.IUnknown
}

func (impl *ButtonBase) AddClick(handler *xaml.RoutedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiButtonBase))
	defer itf.Release()
	v := (*iButtonBase)(unsafe.Pointer(itf))
	return v.AddClick(handler)
}

func (impl *ButtonBase) RemoveClick(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiButtonBase))
	defer itf.Release()
	v := (*iButtonBase)(unsafe.Pointer(itf))
	return v.RemoveClick(token)
}

const GUIDiButtonBase string = "fa002c1a-494e-46cf-91d4-e14a8d798674"
const SignatureiButtonBase string = "{fa002c1a-494e-46cf-91d4-e14a8d798674}"

type iButtonBase struct {
	ole.IInspectable
}

type iButtonBaseVtbl struct {
	ole.IInspectableVtbl

	GetClickMode        uintptr
	SetClickMode        uintptr
	GetIsPointerOver    uintptr
	GetIsPressed        uintptr
	GetCommand          uintptr
	SetCommand          uintptr
	GetCommandParameter uintptr
	SetCommandParameter uintptr
	AddClick            uintptr
	RemoveClick         uintptr
}

func (v *iButtonBase) VTable() *iButtonBaseVtbl {
	return (*iButtonBaseVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iButtonBase) AddClick(handler *xaml.RoutedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddClick,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in xaml.RoutedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iButtonBase) RemoveClick(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveClick,
		uintptr(unsafe.Pointer(v)),                  // this
		uintptr(*(*uint64)(unsafe.Pointer(&token))), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
