// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package primitives

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureFlyoutBase string = "rc(Windows.UI.Xaml.Controls.Primitives.FlyoutBase;{723eea0b-d12e-430d-a9f0-9bb32bbf9913})"

type FlyoutBase struct {
	ole.IUnknown
}

func (impl *FlyoutBase) SetPlacement(value FlyoutPlacementMode) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFlyoutBase))
	defer itf.Release()
	v := (*iFlyoutBase)(unsafe.Pointer(itf))
	return v.SetPlacement(value)
}

func (impl *FlyoutBase) AddClosed(handler *foundation.EventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFlyoutBase))
	defer itf.Release()
	v := (*iFlyoutBase)(unsafe.Pointer(itf))
	return v.AddClosed(handler)
}

func (impl *FlyoutBase) RemoveClosed(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFlyoutBase))
	defer itf.Release()
	v := (*iFlyoutBase)(unsafe.Pointer(itf))
	return v.RemoveClosed(token)
}

func (impl *FlyoutBase) Hide() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFlyoutBase))
	defer itf.Release()
	v := (*iFlyoutBase)(unsafe.Pointer(itf))
	return v.Hide()
}

const GUIDiFlyoutBase string = "723eea0b-d12e-430d-a9f0-9bb32bbf9913"
const SignatureiFlyoutBase string = "{723eea0b-d12e-430d-a9f0-9bb32bbf9913}"

type iFlyoutBase struct {
	ole.IInspectable
}

type iFlyoutBaseVtbl struct {
	ole.IInspectableVtbl

	GetPlacement  uintptr
	SetPlacement  uintptr
	AddOpened     uintptr
	RemoveOpened  uintptr
	AddClosed     uintptr
	RemoveClosed  uintptr
	AddOpening    uintptr
	RemoveOpening uintptr
	ShowAt        uintptr
	Hide          uintptr
}

func (v *iFlyoutBase) VTable() *iFlyoutBaseVtbl {
	return (*iFlyoutBaseVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iFlyoutBase) SetPlacement(value FlyoutPlacementMode) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPlacement,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in FlyoutPlacementMode
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFlyoutBase) AddClosed(handler *foundation.EventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddClosed,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.EventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iFlyoutBase) RemoveClosed(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveClosed,
		uintptr(unsafe.Pointer(v)),                  // this
		uintptr(*(*uint64)(unsafe.Pointer(&token))), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFlyoutBase) Hide() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Hide,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiFlyoutBase2 string = "f82b435e-65b3-41c6-a9e2-77b67bc4c00c"
const SignatureiFlyoutBase2 string = "{f82b435e-65b3-41c6-a9e2-77b67bc4c00c}"

type iFlyoutBase2 struct {
	ole.IInspectable
}

type iFlyoutBase2Vtbl struct {
	ole.IInspectableVtbl

	GetTarget                  uintptr
	GetAllowFocusOnInteraction uintptr
	SetAllowFocusOnInteraction uintptr
	GetLightDismissOverlayMode uintptr
	SetLightDismissOverlayMode uintptr
	GetAllowFocusWhenDisabled  uintptr
	SetAllowFocusWhenDisabled  uintptr
	GetElementSoundMode        uintptr
	SetElementSoundMode        uintptr
	AddClosing                 uintptr
	RemoveClosing              uintptr
}

func (v *iFlyoutBase2) VTable() *iFlyoutBase2Vtbl {
	return (*iFlyoutBase2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBase3 string = "a89c9712-48e0-4240-95b9-0dfd0826a8d3"
const SignatureiFlyoutBase3 string = "{a89c9712-48e0-4240-95b9-0dfd0826a8d3}"

type iFlyoutBase3 struct {
	ole.IInspectable
}

type iFlyoutBase3Vtbl struct {
	ole.IInspectableVtbl

	GetOverlayInputPassThroughElement uintptr
	SetOverlayInputPassThroughElement uintptr
}

func (v *iFlyoutBase3) VTable() *iFlyoutBase3Vtbl {
	return (*iFlyoutBase3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBase4 string = "e3897d69-a37f-4828-9b70-0ef67c03b5f8"
const SignatureiFlyoutBase4 string = "{e3897d69-a37f-4828-9b70-0ef67c03b5f8}"

type iFlyoutBase4 struct {
	ole.IInspectable
}

type iFlyoutBase4Vtbl struct {
	ole.IInspectableVtbl

	TryInvokeKeyboardAccelerator uintptr
}

func (v *iFlyoutBase4) VTable() *iFlyoutBase4Vtbl {
	return (*iFlyoutBase4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBase5 string = "ad3ec0c7-12bb-5a73-b78e-105192ca73d6"
const SignatureiFlyoutBase5 string = "{ad3ec0c7-12bb-5a73-b78e-105192ca73d6}"

type iFlyoutBase5 struct {
	ole.IInspectable
}

type iFlyoutBase5Vtbl struct {
	ole.IInspectableVtbl

	GetShowMode                          uintptr
	SetShowMode                          uintptr
	GetInputDevicePrefersPrimaryCommands uintptr
	GetAreOpenCloseAnimationsEnabled     uintptr
	SetAreOpenCloseAnimationsEnabled     uintptr
	GetIsOpen                            uintptr
	ShowAt                               uintptr
}

func (v *iFlyoutBase5) VTable() *iFlyoutBase5Vtbl {
	return (*iFlyoutBase5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBase6 string = "5399de8c-06cc-5b52-b65a-ff9322d1c940"
const SignatureiFlyoutBase6 string = "{5399de8c-06cc-5b52-b65a-ff9322d1c940}"

type iFlyoutBase6 struct {
	ole.IInspectable
}

type iFlyoutBase6Vtbl struct {
	ole.IInspectableVtbl

	GetShouldConstrainToRootBounds uintptr
	SetShouldConstrainToRootBounds uintptr
	GetIsConstrainedToRootBounds   uintptr
	GetXamlRoot                    uintptr
	SetXamlRoot                    uintptr
}

func (v *iFlyoutBase6) VTable() *iFlyoutBase6Vtbl {
	return (*iFlyoutBase6Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBaseOverrides string = "101dec86-6f4d-45a4-9d0e-3ece6f16977e"
const SignatureiFlyoutBaseOverrides string = "{101dec86-6f4d-45a4-9d0e-3ece6f16977e}"

type iFlyoutBaseOverrides struct {
	ole.IInspectable
}

type iFlyoutBaseOverridesVtbl struct {
	ole.IInspectableVtbl

	CreatePresenter uintptr
}

func (v *iFlyoutBaseOverrides) VTable() *iFlyoutBaseOverridesVtbl {
	return (*iFlyoutBaseOverridesVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFlyoutBaseOverrides4 string = "a6bfd04d-5ff3-4418-add8-4042a88d2da5"
const SignatureiFlyoutBaseOverrides4 string = "{a6bfd04d-5ff3-4418-add8-4042a88d2da5}"

type iFlyoutBaseOverrides4 struct {
	ole.IInspectable
}

type iFlyoutBaseOverrides4Vtbl struct {
	ole.IInspectableVtbl

	OnProcessKeyboardAccelerators uintptr
}

func (v *iFlyoutBaseOverrides4) VTable() *iFlyoutBaseOverrides4Vtbl {
	return (*iFlyoutBaseOverrides4Vtbl)(unsafe.Pointer(v.RawVTable))
}
