// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package primitives

type FlyoutPlacementMode int32

const SignatureFlyoutPlacementMode string = "enum(Windows.UI.Xaml.Controls.Primitives.FlyoutPlacementMode;i4)"

const (
	FlyoutPlacementModeTop                    FlyoutPlacementMode = 0
	FlyoutPlacementModeBottom                 FlyoutPlacementMode = 1
	FlyoutPlacementModeLeft                   FlyoutPlacementMode = 2
	FlyoutPlacementModeRight                  FlyoutPlacementMode = 3
	FlyoutPlacementModeFull                   FlyoutPlacementMode = 4
	FlyoutPlacementModeTopEdgeAlignedLeft     FlyoutPlacementMode = 5
	FlyoutPlacementModeTopEdgeAlignedRight    FlyoutPlacementMode = 6
	FlyoutPlacementModeBottomEdgeAlignedLeft  FlyoutPlacementMode = 7
	FlyoutPlacementModeBottomEdgeAlignedRight FlyoutPlacementMode = 8
	FlyoutPlacementModeLeftEdgeAlignedTop     FlyoutPlacementMode = 9
	FlyoutPlacementModeLeftEdgeAlignedBottom  FlyoutPlacementMode = 10
	FlyoutPlacementModeRightEdgeAlignedTop    FlyoutPlacementMode = 11
	FlyoutPlacementModeRightEdgeAlignedBottom FlyoutPlacementMode = 12
	FlyoutPlacementModeAuto                   FlyoutPlacementMode = 13
)
