// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package system

import (
	"sync"
	"time"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/internal/delegate"
	"github.com/saltosystems/winrt-go/internal/kernel32"
)

const GUIDDispatcherQueueHandler string = "dfa2dc9c-1a2d-4917-98f2-939af1d6e0c8"
const SignatureDispatcherQueueHandler string = "delegate({dfa2dc9c-1a2d-4917-98f2-939af1d6e0c8})"

type DispatcherQueueHandler struct {
	ole.IUnknown
	sync.Mutex
	refs uintptr
	IID  ole.GUID
}

type DispatcherQueueHandlerVtbl struct {
	ole.IUnknownVtbl
	Invoke uintptr
}

type DispatcherQueueHandlerCallback func(instance *DispatcherQueueHandler)

var callbacksDispatcherQueueHandler = &dispatcherQueueHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]DispatcherQueueHandlerCallback),
}

var releaseChannelsDispatcherQueueHandler = &dispatcherQueueHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewDispatcherQueueHandler(iid *ole.GUID, callback DispatcherQueueHandlerCallback) *DispatcherQueueHandler {
	// create type instance
	size := unsafe.Sizeof(*(*DispatcherQueueHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*DispatcherQueueHandler)(instPtr)

	// get the callbacks for the VTable
	callbacks := delegate.RegisterCallbacks(instPtr, inst)

	// the VTable should also be allocated in the heap
	sizeVTable := unsafe.Sizeof(*(*DispatcherQueueHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*DispatcherQueueHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = ole.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	// Initialize all properties: the malloc may contain garbage
	inst.IID = *iid // copy contents
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksDispatcherQueueHandler.add(unsafe.Pointer(inst), callback)

	// See the docs in the releaseChannelsDispatcherQueueHandler struct
	releaseChannelsDispatcherQueueHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *DispatcherQueueHandler) GetIID() *ole.GUID {
	return &r.IID
}

// addRef increments the reference counter by one
func (r *DispatcherQueueHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

// removeRef decrements the reference counter by one. If it was already zero, it will just return zero.
func (r *DispatcherQueueHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()

	if r.refs > 0 {
		r.refs--
	}

	return r.refs
}

func (instance *DispatcherQueueHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {

	// See the quote above.
	if callback, ok := callbacksDispatcherQueueHandler.get(instancePtr); ok {
		callback(instance)
	}
	return ole.S_OK
}

func (instance *DispatcherQueueHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *DispatcherQueueHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		// We're done.
		instancePtr := unsafe.Pointer(instance)
		callbacksDispatcherQueueHandler.delete(instancePtr)

		// stop release channels used to avoid
		// https://github.com/golang/go/issues/55015
		releaseChannelsDispatcherQueueHandler.release(instancePtr)

		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type dispatcherQueueHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]DispatcherQueueHandlerCallback
}

func (m *dispatcherQueueHandlerCallbacks) add(p unsafe.Pointer, v DispatcherQueueHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.callbacks[p] = v
}

func (m *dispatcherQueueHandlerCallbacks) get(p unsafe.Pointer) (DispatcherQueueHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	v, ok := m.callbacks[p]
	return v, ok
}

func (m *dispatcherQueueHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	delete(m.callbacks, p)
}

// typedEventHandlerReleaseChannels keeps a map with channels
// used to keep a goroutine alive during the lifecycle of this object.
// This is required to avoid causing a deadlock error.
// See this: https://github.com/golang/go/issues/55015
type dispatcherQueueHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *dispatcherQueueHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		// we need a timer to trick the go runtime into
		// thinking there's still something going on here
		// but we are only really interested in <-c
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *dispatcherQueueHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
