// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package system

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureDispatcherQueue string = "rc(Windows.System.DispatcherQueue;{603e88e4-a338-4ffe-a457-a5cfb9ceb899})"

type DispatcherQueue struct {
	ole.IUnknown
}

func (impl *DispatcherQueue) TryEnqueue(callback *DispatcherQueueHandler) (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDispatcherQueue))
	defer itf.Release()
	v := (*iDispatcherQueue)(unsafe.Pointer(itf))
	return v.TryEnqueue(callback)
}

const GUIDiDispatcherQueue string = "603e88e4-a338-4ffe-a457-a5cfb9ceb899"
const SignatureiDispatcherQueue string = "{603e88e4-a338-4ffe-a457-a5cfb9ceb899}"

type iDispatcherQueue struct {
	ole.IInspectable
}

type iDispatcherQueueVtbl struct {
	ole.IInspectableVtbl

	CreateTimer             uintptr
	TryEnqueue              uintptr
	TryEnqueueWithPriority  uintptr
	AddShutdownStarting     uintptr
	RemoveShutdownStarting  uintptr
	AddShutdownCompleted    uintptr
	RemoveShutdownCompleted uintptr
}

func (v *iDispatcherQueue) VTable() *iDispatcherQueueVtbl {
	return (*iDispatcherQueueVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDispatcherQueue) TryEnqueue(callback *DispatcherQueueHandler) (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryEnqueue,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(callback)), // in DispatcherQueueHandler
		uintptr(unsafe.Pointer(&out)),     // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiDispatcherQueue2 string = "c822c647-30ef-506e-bd1e-a647ae6675ff"
const SignatureiDispatcherQueue2 string = "{c822c647-30ef-506e-bd1e-a647ae6675ff}"

type iDispatcherQueue2 struct {
	ole.IInspectable
}

type iDispatcherQueue2Vtbl struct {
	ole.IInspectableVtbl

	GetHasThreadAccess uintptr
}

func (v *iDispatcherQueue2) VTable() *iDispatcherQueue2Vtbl {
	return (*iDispatcherQueue2Vtbl)(unsafe.Pointer(v.RawVTable))
}
