// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package system

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureDispatcherQueueController string = "rc(Windows.System.DispatcherQueueController;{22f34e66-50db-4e36-a98d-61c01b384d20})"

type DispatcherQueueController struct {
	ole.IUnknown
}

func (impl *DispatcherQueueController) GetDispatcherQueue() (*DispatcherQueue, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDispatcherQueueController))
	defer itf.Release()
	v := (*iDispatcherQueueController)(unsafe.Pointer(itf))
	return v.GetDispatcherQueue()
}

const GUIDiDispatcherQueueController string = "22f34e66-50db-4e36-a98d-61c01b384d20"
const SignatureiDispatcherQueueController string = "{22f34e66-50db-4e36-a98d-61c01b384d20}"

type iDispatcherQueueController struct {
	ole.IInspectable
}

type iDispatcherQueueControllerVtbl struct {
	ole.IInspectableVtbl

	GetDispatcherQueue uintptr
	ShutdownQueueAsync uintptr
}

func (v *iDispatcherQueueController) VTable() *iDispatcherQueueControllerVtbl {
	return (*iDispatcherQueueControllerVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDispatcherQueueController) GetDispatcherQueue() (*DispatcherQueue, error) {
	var out *DispatcherQueue
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDispatcherQueue,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DispatcherQueue
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
