// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureBrush string = "rc(Windows.UI.Xaml.Media.Brush;{8806a321-1e06-422c-a1cc-01696559e021})"

type Brush struct {
	ole.IUnknown
}

const GUIDiBrush string = "8806a321-1e06-422c-a1cc-01696559e021"
const SignatureiBrush string = "{8806a321-1e06-422c-a1cc-01696559e021}"

type iBrush struct {
	ole.IInspectable
}

type iBrushVtbl struct {
	ole.IInspectableVtbl

	GetOpacity           uintptr
	SetOpacity           uintptr
	GetTransform         uintptr
	SetTransform         uintptr
	GetRelativeTransform uintptr
	SetRelativeTransform uintptr
}

func (v *iBrush) VTable() *iBrushVtbl {
	return (*iBrushVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiBrushOverrides2 string = "d092b151-d83b-5a81-a71e-a1c7f8ad6963"
const SignatureiBrushOverrides2 string = "{d092b151-d83b-5a81-a71e-a1c7f8ad6963}"

type iBrushOverrides2 struct {
	ole.IInspectable
}

type iBrushOverrides2Vtbl struct {
	ole.IInspectableVtbl

	PopulatePropertyInfoOverride uintptr
}

func (v *iBrushOverrides2) VTable() *iBrushOverrides2Vtbl {
	return (*iBrushOverrides2Vtbl)(unsafe.Pointer(v.RawVTable))
}
