// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureImageSource string = "rc(Windows.UI.Xaml.Media.ImageSource;{737ef309-ea41-4d96-a71c-98e98efcab07})"

type ImageSource struct {
	ole.IUnknown
}

const GUIDiImageSource string = "737ef309-ea41-4d96-a71c-98e98efcab07"
const SignatureiImageSource string = "{737ef309-ea41-4d96-a71c-98e98efcab07}"

type iImageSource struct {
	ole.IInspectable
}

type iImageSourceVtbl struct {
	ole.IInspectableVtbl
}

func (v *iImageSource) VTable() *iImageSourceVtbl {
	return (*iImageSourceVtbl)(unsafe.Pointer(v.RawVTable))
}
