// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureImageBrush string = "rc(Windows.UI.Xaml.Media.ImageBrush;{9fd11377-c12a-4493-bf7d-f3a8ad74b554})"

type ImageBrush struct {
	ole.IUnknown
}

func NewImageBrush() (*ImageBrush, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Media.ImageBrush")
	if err != nil {
		return nil, err
	}
	return (*ImageBrush)(unsafe.Pointer(inspectable)), nil
}

func (impl *ImageBrush) SetImageSource(value *ImageSource) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiImageBrush))
	defer itf.Release()
	v := (*iImageBrush)(unsafe.Pointer(itf))
	return v.SetImageSource(value)
}

const GUIDiImageBrush string = "9fd11377-c12a-4493-bf7d-f3a8ad74b554"
const SignatureiImageBrush string = "{9fd11377-c12a-4493-bf7d-f3a8ad74b554}"

type iImageBrush struct {
	ole.IInspectable
}

type iImageBrushVtbl struct {
	ole.IInspectableVtbl

	GetImageSource    uintptr
	SetImageSource    uintptr
	AddImageFailed    uintptr
	RemoveImageFailed uintptr
	AddImageOpened    uintptr
	RemoveImageOpened uintptr
}

func (v *iImageBrush) VTable() *iImageBrushVtbl {
	return (*iImageBrushVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iImageBrush) SetImageSource(value *ImageSource) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetImageSource,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in ImageSource
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
