// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui"
)

const SignatureSolidColorBrush string = "rc(Windows.UI.Xaml.Media.SolidColorBrush;{9d850850-66f3-48df-9a8f-824bd5e070af})"

type SolidColorBrush struct {
	ole.IUnknown
}

func NewSolidColorBrush() (*SolidColorBrush, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Media.SolidColorBrush")
	if err != nil {
		return nil, err
	}
	return (*SolidColorBrush)(unsafe.Pointer(inspectable)), nil
}

func (impl *SolidColorBrush) SetColor(value ui.Color) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSolidColorBrush))
	defer itf.Release()
	v := (*iSolidColorBrush)(unsafe.Pointer(itf))
	return v.SetColor(value)
}

const GUIDiSolidColorBrush string = "9d850850-66f3-48df-9a8f-824bd5e070af"
const SignatureiSolidColorBrush string = "{9d850850-66f3-48df-9a8f-824bd5e070af}"

type iSolidColorBrush struct {
	ole.IInspectable
}

type iSolidColorBrushVtbl struct {
	ole.IInspectableVtbl

	GetColor uintptr
	SetColor uintptr
}

func (v *iSolidColorBrush) VTable() *iSolidColorBrushVtbl {
	return (*iSolidColorBrushVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSolidColorBrush) SetColor(value ui.Color) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetColor,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in ui.Color
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
