// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

type Stretch int32

const SignatureStretch string = "enum(Windows.UI.Xaml.Media.Stretch;i4)"

const (
	StretchNone          Stretch = 0
	StretchFill          Stretch = 1
	StretchUniform       Stretch = 2
	StretchUniformToFill Stretch = 3
)
