// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package media

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureTileBrush string = "rc(Windows.UI.Xaml.Media.TileBrush;{c201cf06-cd84-48a5-9607-664d7361cd61})"

type TileBrush struct {
	ole.IUnknown
}

func (impl *TileBrush) SetStretch(value Stretch) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTileBrush))
	defer itf.Release()
	v := (*iTileBrush)(unsafe.Pointer(itf))
	return v.SetStretch(value)
}

const GUIDiTileBrush string = "c201cf06-cd84-48a5-9607-664d7361cd61"
const SignatureiTileBrush string = "{c201cf06-cd84-48a5-9607-664d7361cd61}"

type iTileBrush struct {
	ole.IInspectable
}

type iTileBrushVtbl struct {
	ole.IInspectableVtbl

	GetAlignmentX uintptr
	SetAlignmentX uintptr
	GetAlignmentY uintptr
	SetAlignmentY uintptr
	GetStretch    uintptr
	SetStretch    uintptr
}

func (v *iTileBrush) VTable() *iTileBrushVtbl {
	return (*iTileBrushVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iTileBrush) SetStretch(value Stretch) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetStretch,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in Stretch
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
