// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package credentials

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignaturePasswordVault string = "rc(Windows.Security.Credentials.PasswordVault;{61fd2c0b-c8d4-48c1-a54f-bc5a64205af2})"

type PasswordVault struct {
	ole.IUnknown
}

func NewPasswordVault() (*PasswordVault, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Credentials.PasswordVault")
	if err != nil {
		return nil, err
	}
	return (*PasswordVault)(unsafe.Pointer(inspectable)), nil
}

func (impl *PasswordVault) Add(credential *PasswordCredential) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordVault))
	defer itf.Release()
	v := (*iPasswordVault)(unsafe.Pointer(itf))
	return v.Add(credential)
}

func (impl *PasswordVault) Remove(credential *PasswordCredential) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordVault))
	defer itf.Release()
	v := (*iPasswordVault)(unsafe.Pointer(itf))
	return v.Remove(credential)
}

func (impl *PasswordVault) Retrieve(resource string, userName string) (*PasswordCredential, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordVault))
	defer itf.Release()
	v := (*iPasswordVault)(unsafe.Pointer(itf))
	return v.Retrieve(resource, userName)
}

func (impl *PasswordVault) FindAllByResource(resource string) (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordVault))
	defer itf.Release()
	v := (*iPasswordVault)(unsafe.Pointer(itf))
	return v.FindAllByResource(resource)
}

const GUIDiPasswordVault string = "61fd2c0b-c8d4-48c1-a54f-bc5a64205af2"
const SignatureiPasswordVault string = "{61fd2c0b-c8d4-48c1-a54f-bc5a64205af2}"

type iPasswordVault struct {
	ole.IInspectable
}

type iPasswordVaultVtbl struct {
	ole.IInspectableVtbl

	Add               uintptr
	Remove            uintptr
	Retrieve          uintptr
	FindAllByResource uintptr
	FindAllByUserName uintptr
	RetrieveAll       uintptr
}

func (v *iPasswordVault) VTable() *iPasswordVaultVtbl {
	return (*iPasswordVaultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPasswordVault) Add(credential *PasswordCredential) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Add,
		uintptr(unsafe.Pointer(v)),          // this
		uintptr(unsafe.Pointer(credential)), // in PasswordCredential
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iPasswordVault) Remove(credential *PasswordCredential) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Remove,
		uintptr(unsafe.Pointer(v)),          // this
		uintptr(unsafe.Pointer(credential)), // in PasswordCredential
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iPasswordVault) Retrieve(resource string, userName string) (*PasswordCredential, error) {
	var out *PasswordCredential
	resourceHStr, err := ole.NewHString(resource)
	if err != nil {
		return nil, err
	}
	userNameHStr, err := ole.NewHString(userName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().Retrieve,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(resourceHStr),         // in string
		uintptr(userNameHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out PasswordCredential
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iPasswordVault) FindAllByResource(resource string) (*collections.IVectorView, error) {
	var out *collections.IVectorView
	resourceHStr, err := ole.NewHString(resource)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().FindAllByResource,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(resourceHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
