// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package credentials

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignaturePasswordCredential string = "rc(Windows.Security.Credentials.PasswordCredential;{6ab18989-c720-41a7-a6c1-feadb36329a0})"

type PasswordCredential struct {
	ole.IUnknown
}

func NewPasswordCredential() (*PasswordCredential, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Credentials.PasswordCredential")
	if err != nil {
		return nil, err
	}
	return (*PasswordCredential)(unsafe.Pointer(inspectable)), nil
}

func (impl *PasswordCredential) GetResource() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordCredential))
	defer itf.Release()
	v := (*iPasswordCredential)(unsafe.Pointer(itf))
	return v.GetResource()
}

func (impl *PasswordCredential) GetUserName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordCredential))
	defer itf.Release()
	v := (*iPasswordCredential)(unsafe.Pointer(itf))
	return v.GetUserName()
}

func (impl *PasswordCredential) GetPassword() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordCredential))
	defer itf.Release()
	v := (*iPasswordCredential)(unsafe.Pointer(itf))
	return v.GetPassword()
}

func (impl *PasswordCredential) RetrievePassword() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordCredential))
	defer itf.Release()
	v := (*iPasswordCredential)(unsafe.Pointer(itf))
	return v.RetrievePassword()
}

const GUIDiPasswordCredential string = "6ab18989-c720-41a7-a6c1-feadb36329a0"
const SignatureiPasswordCredential string = "{6ab18989-c720-41a7-a6c1-feadb36329a0}"

type iPasswordCredential struct {
	ole.IInspectable
}

type iPasswordCredentialVtbl struct {
	ole.IInspectableVtbl

	GetResource      uintptr
	SetResource      uintptr
	GetUserName      uintptr
	SetUserName      uintptr
	GetPassword      uintptr
	SetPassword      uintptr
	RetrievePassword uintptr
	GetProperties    uintptr
}

func (v *iPasswordCredential) VTable() *iPasswordCredentialVtbl {
	return (*iPasswordCredentialVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPasswordCredential) GetResource() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetResource,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iPasswordCredential) GetUserName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUserName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iPasswordCredential) GetPassword() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPassword,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iPasswordCredential) RetrievePassword() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RetrievePassword,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiCredentialFactory string = "54ef13a1-bf26-47b5-97dd-de779b7cad58"
const SignatureiCredentialFactory string = "{54ef13a1-bf26-47b5-97dd-de779b7cad58}"

type iCredentialFactory struct {
	ole.IInspectable
}

type iCredentialFactoryVtbl struct {
	ole.IInspectableVtbl

	PasswordCredentialCreatePasswordCredential uintptr
}

func (v *iCredentialFactory) VTable() *iCredentialFactoryVtbl {
	return (*iCredentialFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func PasswordCredentialCreatePasswordCredential(resource string, userName string, password string) (*PasswordCredential, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Credentials.PasswordCredential", ole.NewGUID(GUIDiCredentialFactory))
	if err != nil {
		return nil, err
	}
	v := (*iCredentialFactory)(unsafe.Pointer(inspectable))

	var out *PasswordCredential
	resourceHStr, err := ole.NewHString(resource)
	if err != nil {
		return nil, err
	}
	userNameHStr, err := ole.NewHString(userName)
	if err != nil {
		return nil, err
	}
	passwordHStr, err := ole.NewHString(password)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().PasswordCredentialCreatePasswordCredential,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(resourceHStr),         // in string
		uintptr(userNameHStr),         // in string
		uintptr(passwordHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out PasswordCredential
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
