// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureMediaSource string = "rc(Windows.Media.Core.MediaSource;{2eb61048-655f-4c37-b813-b4e45dfa0abe})"

type MediaSource struct {
	ole.IUnknown
}

const GUIDiMediaSource2 string = "2eb61048-655f-4c37-b813-b4e45dfa0abe"
const SignatureiMediaSource2 string = "{2eb61048-655f-4c37-b813-b4e45dfa0abe}"

type iMediaSource2 struct {
	ole.IInspectable
}

type iMediaSource2Vtbl struct {
	ole.IInspectableVtbl

	AddOpenOperationCompleted      uintptr
	RemoveOpenOperationCompleted   uintptr
	GetCustomProperties            uintptr
	GetDuration                    uintptr
	GetIsOpen                      uintptr
	GetExternalTimedTextSources    uintptr
	GetExternalTimedMetadataTracks uintptr
}

func (v *iMediaSource2) VTable() *iMediaSource2Vtbl {
	return (*iMediaSource2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiMediaSource3 string = "b59f0d9b-4b6e-41ed-bbb4-7c7509a994ad"
const SignatureiMediaSource3 string = "{b59f0d9b-4b6e-41ed-bbb4-7c7509a994ad}"

type iMediaSource3 struct {
	ole.IInspectable
}

type iMediaSource3Vtbl struct {
	ole.IInspectableVtbl

	AddStateChanged    uintptr
	RemoveStateChanged uintptr
	GetState           uintptr
	Reset              uintptr
}

func (v *iMediaSource3) VTable() *iMediaSource3Vtbl {
	return (*iMediaSource3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiMediaSource4 string = "bdafad57-8eff-4c63-85a6-84de0ae3e4f2"
const SignatureiMediaSource4 string = "{bdafad57-8eff-4c63-85a6-84de0ae3e4f2}"

type iMediaSource4 struct {
	ole.IInspectable
}

type iMediaSource4Vtbl struct {
	ole.IInspectableVtbl

	GetAdaptiveMediaSource uintptr
	GetMediaStreamSource   uintptr
	GetMseStreamSource     uintptr
	GetUri                 uintptr
	OpenAsync              uintptr
}

func (v *iMediaSource4) VTable() *iMediaSource4Vtbl {
	return (*iMediaSource4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiMediaSource5 string = "331a22ae-ed2e-4a22-94c8-b743a92b3022"
const SignatureiMediaSource5 string = "{331a22ae-ed2e-4a22-94c8-b743a92b3022}"

type iMediaSource5 struct {
	ole.IInspectable
}

type iMediaSource5Vtbl struct {
	ole.IInspectableVtbl

	GetDownloadOperation uintptr
}

func (v *iMediaSource5) VTable() *iMediaSource5Vtbl {
	return (*iMediaSource5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiMediaSourceStatics string = "f77d6fa4-4652-410e-b1d8-e9a5e245a45c"
const SignatureiMediaSourceStatics string = "{f77d6fa4-4652-410e-b1d8-e9a5e245a45c}"

type iMediaSourceStatics struct {
	ole.IInspectable
}

type iMediaSourceStaticsVtbl struct {
	ole.IInspectableVtbl

	MediaSourceCreateFromAdaptiveMediaSource uintptr
	MediaSourceCreateFromMediaStreamSource   uintptr
	MediaSourceCreateFromMseStreamSource     uintptr
	MediaSourceCreateFromIMediaSource        uintptr
	MediaSourceCreateFromStorageFile         uintptr
	MediaSourceCreateFromStream              uintptr
	MediaSourceCreateFromStreamReference     uintptr
	MediaSourceCreateFromUri                 uintptr
}

func (v *iMediaSourceStatics) VTable() *iMediaSourceStaticsVtbl {
	return (*iMediaSourceStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func MediaSourceCreateFromUri(uri *foundation.Uri) (*MediaSource, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Core.MediaSource", ole.NewGUID(GUIDiMediaSourceStatics))
	if err != nil {
		return nil, err
	}
	v := (*iMediaSourceStatics)(unsafe.Pointer(inspectable))

	var out *MediaSource
	hr, _, _ := syscall.SyscallN(
		v.VTable().MediaSourceCreateFromUri,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(uri)),  // in foundation.Uri
		uintptr(unsafe.Pointer(&out)), // out MediaSource
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
