// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package automation

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
)

const SignatureAutomationProperties string = "rc(Windows.UI.Xaml.Automation.AutomationProperties;{68d7232c-e622-48e9-af0b-1ffa33cc5cba})"

type AutomationProperties struct {
	ole.IUnknown
}

const GUIDiAutomationProperties string = "68d7232c-e622-48e9-af0b-1ffa33cc5cba"
const SignatureiAutomationProperties string = "{68d7232c-e622-48e9-af0b-1ffa33cc5cba}"

type iAutomationProperties struct {
	ole.IInspectable
}

type iAutomationPropertiesVtbl struct {
	ole.IInspectableVtbl
}

func (v *iAutomationProperties) VTable() *iAutomationPropertiesVtbl {
	return (*iAutomationPropertiesVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiAutomationPropertiesStatics string = "b618fd7b-32d0-4970-9c42-7c039ac7be78"
const SignatureiAutomationPropertiesStatics string = "{b618fd7b-32d0-4970-9c42-7c039ac7be78}"

type iAutomationPropertiesStatics struct {
	ole.IInspectable
}

type iAutomationPropertiesStaticsVtbl struct {
	ole.IInspectableVtbl

	AutomationPropertiesGetAcceleratorKeyProperty    uintptr
	AutomationPropertiesGetAcceleratorKey            uintptr
	AutomationPropertiesSetAcceleratorKey            uintptr
	AutomationPropertiesGetAccessKeyProperty         uintptr
	AutomationPropertiesGetAccessKey                 uintptr
	AutomationPropertiesSetAccessKey                 uintptr
	AutomationPropertiesGetAutomationIdProperty      uintptr
	AutomationPropertiesGetAutomationId              uintptr
	AutomationPropertiesSetAutomationId              uintptr
	AutomationPropertiesGetHelpTextProperty          uintptr
	AutomationPropertiesGetHelpText                  uintptr
	AutomationPropertiesSetHelpText                  uintptr
	AutomationPropertiesGetIsRequiredForFormProperty uintptr
	AutomationPropertiesGetIsRequiredForForm         uintptr
	AutomationPropertiesSetIsRequiredForForm         uintptr
	AutomationPropertiesGetItemStatusProperty        uintptr
	AutomationPropertiesGetItemStatus                uintptr
	AutomationPropertiesSetItemStatus                uintptr
	AutomationPropertiesGetItemTypeProperty          uintptr
	AutomationPropertiesGetItemType                  uintptr
	AutomationPropertiesSetItemType                  uintptr
	AutomationPropertiesGetLabeledByProperty         uintptr
	AutomationPropertiesGetLabeledBy                 uintptr
	AutomationPropertiesSetLabeledBy                 uintptr
	AutomationPropertiesGetNameProperty              uintptr
	AutomationPropertiesGetName                      uintptr
	AutomationPropertiesSetName                      uintptr
	AutomationPropertiesGetLiveSettingProperty       uintptr
	AutomationPropertiesGetLiveSetting               uintptr
	AutomationPropertiesSetLiveSetting               uintptr
}

func (v *iAutomationPropertiesStatics) VTable() *iAutomationPropertiesStaticsVtbl {
	return (*iAutomationPropertiesStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func AutomationPropertiesSetName(element *xaml.DependencyObject, value string) error {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Xaml.Automation.AutomationProperties", ole.NewGUID(GUIDiAutomationPropertiesStatics))
	if err != nil {
		return err
	}
	v := (*iAutomationPropertiesStatics)(unsafe.Pointer(inspectable))

	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().AutomationPropertiesSetName,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(element)), // in xaml.DependencyObject
		uintptr(valueHStr),               // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
