// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package hosting

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
)

const SignatureDesktopWindowXamlSource string = "rc(Windows.UI.Xaml.Hosting.DesktopWindowXamlSource;{d585bfe1-00ff-51be-ba1d-a1329956ea0a})"

type DesktopWindowXamlSource struct {
	ole.IUnknown
}

func (impl *DesktopWindowXamlSource) SetContent(value *xaml.UIElement) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiDesktopWindowXamlSource))
	defer itf.Release()
	v := (*iDesktopWindowXamlSource)(unsafe.Pointer(itf))
	return v.SetContent(value)
}

func (impl *DesktopWindowXamlSource) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

const GUIDiDesktopWindowXamlSource string = "d585bfe1-00ff-51be-ba1d-a1329956ea0a"
const SignatureiDesktopWindowXamlSource string = "{d585bfe1-00ff-51be-ba1d-a1329956ea0a}"

type iDesktopWindowXamlSource struct {
	ole.IInspectable
}

type iDesktopWindowXamlSourceVtbl struct {
	ole.IInspectableVtbl

	GetContent               uintptr
	SetContent               uintptr
	GetHasFocus              uintptr
	AddTakeFocusRequested    uintptr
	RemoveTakeFocusRequested uintptr
	AddGotFocus              uintptr
	RemoveGotFocus           uintptr
	NavigateFocus            uintptr
}

func (v *iDesktopWindowXamlSource) VTable() *iDesktopWindowXamlSourceVtbl {
	return (*iDesktopWindowXamlSourceVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iDesktopWindowXamlSource) SetContent(value *xaml.UIElement) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetContent,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in xaml.UIElement
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
