// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package hosting

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureWindowsXamlManager string = "rc(Windows.UI.Xaml.Hosting.WindowsXamlManager;{56096c31-1aa0-5288-8818-6e74a2dcaff5})"

type WindowsXamlManager struct {
	ole.IUnknown
}

func (impl *WindowsXamlManager) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

const GUIDiWindowsXamlManager string = "56096c31-1aa0-5288-8818-6e74a2dcaff5"
const SignatureiWindowsXamlManager string = "{56096c31-1aa0-5288-8818-6e74a2dcaff5}"

type iWindowsXamlManager struct {
	ole.IInspectable
}

type iWindowsXamlManagerVtbl struct {
	ole.IInspectableVtbl
}

func (v *iWindowsXamlManager) VTable() *iWindowsXamlManagerVtbl {
	return (*iWindowsXamlManagerVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiWindowsXamlManagerStatics string = "28258a12-7d82-505b-b210-712b04a58882"
const SignatureiWindowsXamlManagerStatics string = "{28258a12-7d82-505b-b210-712b04a58882}"

type iWindowsXamlManagerStatics struct {
	ole.IInspectable
}

type iWindowsXamlManagerStaticsVtbl struct {
	ole.IInspectableVtbl

	WindowsXamlManagerInitializeForCurrentThread uintptr
}

func (v *iWindowsXamlManagerStatics) VTable() *iWindowsXamlManagerStaticsVtbl {
	return (*iWindowsXamlManagerStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func WindowsXamlManagerInitializeForCurrentThread() (*WindowsXamlManager, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Xaml.Hosting.WindowsXamlManager", ole.NewGUID(GUIDiWindowsXamlManagerStatics))
	if err != nil {
		return nil, err
	}
	v := (*iWindowsXamlManagerStatics)(unsafe.Pointer(inspectable))

	var out *WindowsXamlManager
	hr, _, _ := syscall.SyscallN(
		v.VTable().WindowsXamlManagerInitializeForCurrentThread,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out WindowsXamlManager
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
