// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package shapes

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureEllipse string = "rc(Windows.UI.Xaml.Shapes.Ellipse;{70e05ac4-d38d-4bab-831f-4a22ef52ac86})"

type Ellipse struct {
	ole.IUnknown
}

func NewEllipse() (*Ellipse, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Shapes.Ellipse")
	if err != nil {
		return nil, err
	}
	return (*Ellipse)(unsafe.Pointer(inspectable)), nil
}

const GUIDiEllipse string = "70e05ac4-d38d-4bab-831f-4a22ef52ac86"
const SignatureiEllipse string = "{70e05ac4-d38d-4bab-831f-4a22ef52ac86}"

type iEllipse struct {
	ole.IInspectable
}

type iEllipseVtbl struct {
	ole.IInspectableVtbl
}

func (v *iEllipse) VTable() *iEllipseVtbl {
	return (*iEllipseVtbl)(unsafe.Pointer(v.RawVTable))
}
