// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package shapes

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureShape string = "rc(Windows.UI.Xaml.Shapes.Shape;{786f2b75-9aa0-454d-ae06-a2466e37c832})"

type Shape struct {
	ole.IUnknown
}

func (impl *Shape) SetFill(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiShape))
	defer itf.Release()
	v := (*iShape)(unsafe.Pointer(itf))
	return v.SetFill(value)
}

const GUIDiShape string = "786f2b75-9aa0-454d-ae06-a2466e37c832"
const SignatureiShape string = "{786f2b75-9aa0-454d-ae06-a2466e37c832}"

type iShape struct {
	ole.IInspectable
}

type iShapeVtbl struct {
	ole.IInspectableVtbl

	GetFill               uintptr
	SetFill               uintptr
	GetStroke             uintptr
	SetStroke             uintptr
	GetStrokeMiterLimit   uintptr
	SetStrokeMiterLimit   uintptr
	GetStrokeThickness    uintptr
	SetStrokeThickness    uintptr
	GetStrokeStartLineCap uintptr
	SetStrokeStartLineCap uintptr
	GetStrokeEndLineCap   uintptr
	SetStrokeEndLineCap   uintptr
	GetStrokeLineJoin     uintptr
	SetStrokeLineJoin     uintptr
	GetStrokeDashOffset   uintptr
	SetStrokeDashOffset   uintptr
	GetStrokeDashCap      uintptr
	SetStrokeDashCap      uintptr
	GetStrokeDashArray    uintptr
	SetStrokeDashArray    uintptr
	GetStretch            uintptr
	SetStretch            uintptr
	GetGeometryTransform  uintptr
}

func (v *iShape) VTable() *iShapeVtbl {
	return (*iShapeVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iShape) SetFill(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetFill,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiShape2 string = "97248dba-49f2-49a4-a5dd-164df824db14"
const SignatureiShape2 string = "{97248dba-49f2-49a4-a5dd-164df824db14}"

type iShape2 struct {
	ole.IInspectable
}

type iShape2Vtbl struct {
	ole.IInspectableVtbl

	GetAlphaMask uintptr
}

func (v *iShape2) VTable() *iShape2Vtbl {
	return (*iShape2Vtbl)(unsafe.Pointer(v.RawVTable))
}
