// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

const SignatureCornerRadius string = "struct(Windows.UI.Xaml.CornerRadius;f8;f8;f8;f8)"

type CornerRadius struct {
	TopLeft float64

	TopRight float64

	BottomRight float64

	BottomLeft float64
}
