// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureDependencyObject string = "rc(Windows.UI.Xaml.DependencyObject;{5c526665-f60e-4912-af59-5fe0680f089d})"

type DependencyObject struct {
	ole.IUnknown
}

const GUIDiDependencyObject string = "5c526665-f60e-4912-af59-5fe0680f089d"
const SignatureiDependencyObject string = "{5c526665-f60e-4912-af59-5fe0680f089d}"

type iDependencyObject struct {
	ole.IInspectable
}

type iDependencyObjectVtbl struct {
	ole.IInspectableVtbl

	GetValue              uintptr
	SetValue              uintptr
	ClearValue            uintptr
	ReadLocalValue        uintptr
	GetAnimationBaseValue uintptr
	GetDispatcher         uintptr
}

func (v *iDependencyObject) VTable() *iDependencyObjectVtbl {
	return (*iDependencyObjectVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiDependencyObject2 string = "29fed85d-3d22-43a1-add0-17027c08b212"
const SignatureiDependencyObject2 string = "{29fed85d-3d22-43a1-add0-17027c08b212}"

type iDependencyObject2 struct {
	ole.IInspectable
}

type iDependencyObject2Vtbl struct {
	ole.IInspectableVtbl

	RegisterPropertyChangedCallback   uintptr
	UnregisterPropertyChangedCallback uintptr
}

func (v *iDependencyObject2) VTable() *iDependencyObject2Vtbl {
	return (*iDependencyObject2Vtbl)(unsafe.Pointer(v.RawVTable))
}
