// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type ElementTheme int32

const SignatureElementTheme string = "enum(Windows.UI.Xaml.ElementTheme;i4)"

const (
	ElementThemeDefault ElementTheme = 0
	ElementThemeLight   ElementTheme = 1
	ElementThemeDark    ElementTheme = 2
)
