// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"sync"
	"time"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/internal/delegate"
	"github.com/saltosystems/winrt-go/internal/kernel32"
)

const GUIDExceptionRoutedEventHandler string = "68e0e810-f6ea-42bc-855b-5d9b67e6a262"
const SignatureExceptionRoutedEventHandler string = "delegate({68e0e810-f6ea-42bc-855b-5d9b67e6a262})"

type ExceptionRoutedEventHandler struct {
	ole.IUnknown
	sync.Mutex
	refs uintptr
	IID  ole.GUID
}

type ExceptionRoutedEventHandlerVtbl struct {
	ole.IUnknownVtbl
	Invoke uintptr
}

type ExceptionRoutedEventHandlerCallback func(instance *ExceptionRoutedEventHandler, sender unsafe.Pointer, e *ExceptionRoutedEventArgs)

var callbacksExceptionRoutedEventHandler = &exceptionRoutedEventHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]ExceptionRoutedEventHandlerCallback),
}

var releaseChannelsExceptionRoutedEventHandler = &exceptionRoutedEventHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewExceptionRoutedEventHandler(iid *ole.GUID, callback ExceptionRoutedEventHandlerCallback) *ExceptionRoutedEventHandler {
	// create type instance
	size := unsafe.Sizeof(*(*ExceptionRoutedEventHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*ExceptionRoutedEventHandler)(instPtr)

	// get the callbacks for the VTable
	callbacks := delegate.RegisterCallbacks(instPtr, inst)

	// the VTable should also be allocated in the heap
	sizeVTable := unsafe.Sizeof(*(*ExceptionRoutedEventHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*ExceptionRoutedEventHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = ole.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	// Initialize all properties: the malloc may contain garbage
	inst.IID = *iid // copy contents
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksExceptionRoutedEventHandler.add(unsafe.Pointer(inst), callback)

	// See the docs in the releaseChannelsExceptionRoutedEventHandler struct
	releaseChannelsExceptionRoutedEventHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *ExceptionRoutedEventHandler) GetIID() *ole.GUID {
	return &r.IID
}

// addRef increments the reference counter by one
func (r *ExceptionRoutedEventHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

// removeRef decrements the reference counter by one. If it was already zero, it will just return zero.
func (r *ExceptionRoutedEventHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()

	if r.refs > 0 {
		r.refs--
	}

	return r.refs
}

func (instance *ExceptionRoutedEventHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {
	senderPtr := rawArgs0
	ePtr := rawArgs1

	// See the quote above.
	sender := (unsafe.Pointer)(senderPtr)
	e := (*ExceptionRoutedEventArgs)(ePtr)
	if callback, ok := callbacksExceptionRoutedEventHandler.get(instancePtr); ok {
		callback(instance, sender, e)
	}
	return ole.S_OK
}

func (instance *ExceptionRoutedEventHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *ExceptionRoutedEventHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		// We're done.
		instancePtr := unsafe.Pointer(instance)
		callbacksExceptionRoutedEventHandler.delete(instancePtr)

		// stop release channels used to avoid
		// https://github.com/golang/go/issues/55015
		releaseChannelsExceptionRoutedEventHandler.release(instancePtr)

		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type exceptionRoutedEventHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]ExceptionRoutedEventHandlerCallback
}

func (m *exceptionRoutedEventHandlerCallbacks) add(p unsafe.Pointer, v ExceptionRoutedEventHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.callbacks[p] = v
}

func (m *exceptionRoutedEventHandlerCallbacks) get(p unsafe.Pointer) (ExceptionRoutedEventHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	v, ok := m.callbacks[p]
	return v, ok
}

func (m *exceptionRoutedEventHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	delete(m.callbacks, p)
}

// typedEventHandlerReleaseChannels keeps a map with channels
// used to keep a goroutine alive during the lifecycle of this object.
// This is required to avoid causing a deadlock error.
// See this: https://github.com/golang/go/issues/55015
type exceptionRoutedEventHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *exceptionRoutedEventHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		// we need a timer to trick the go runtime into
		// thinking there's still something going on here
		// but we are only really interested in <-c
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *exceptionRoutedEventHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
