// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureExceptionRoutedEventArgs string = "rc(Windows.UI.Xaml.ExceptionRoutedEventArgs;{dd9ff16a-4b62-4a6c-a49d-0671ef6136be})"

type ExceptionRoutedEventArgs struct {
	ole.IUnknown
}

func (impl *ExceptionRoutedEventArgs) GetErrorMessage() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiExceptionRoutedEventArgs))
	defer itf.Release()
	v := (*iExceptionRoutedEventArgs)(unsafe.Pointer(itf))
	return v.GetErrorMessage()
}

const GUIDiExceptionRoutedEventArgs string = "dd9ff16a-4b62-4a6c-a49d-0671ef6136be"
const SignatureiExceptionRoutedEventArgs string = "{dd9ff16a-4b62-4a6c-a49d-0671ef6136be}"

type iExceptionRoutedEventArgs struct {
	ole.IInspectable
}

type iExceptionRoutedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetErrorMessage uintptr
}

func (v *iExceptionRoutedEventArgs) VTable() *iExceptionRoutedEventArgsVtbl {
	return (*iExceptionRoutedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iExceptionRoutedEventArgs) GetErrorMessage() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetErrorMessage,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
