// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type FocusState int32

const SignatureFocusState string = "enum(Windows.UI.Xaml.FocusState;i4)"

const (
	FocusStateUnfocused    FocusState = 0
	FocusStatePointer      FocusState = 1
	FocusStateKeyboard     FocusState = 2
	FocusStateProgrammatic FocusState = 3
)
