// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureFrameworkElement string = "rc(Windows.UI.Xaml.FrameworkElement;{a391d09b-4a99-4b7c-9d8d-6fa5d01f6fbf})"

type FrameworkElement struct {
	ole.IUnknown
}

func (impl *FrameworkElement) SetWidth(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetWidth(value)
}

func (impl *FrameworkElement) SetHeight(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetHeight(value)
}

func (impl *FrameworkElement) SetMinWidth(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetMinWidth(value)
}

func (impl *FrameworkElement) SetMinHeight(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetMinHeight(value)
}

func (impl *FrameworkElement) SetHorizontalAlignment(value HorizontalAlignment) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetHorizontalAlignment(value)
}

func (impl *FrameworkElement) SetVerticalAlignment(value VerticalAlignment) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetVerticalAlignment(value)
}

func (impl *FrameworkElement) SetMargin(value Thickness) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetMargin(value)
}

func (impl *FrameworkElement) SetName(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.SetName(value)
}

func (impl *FrameworkElement) FindName(name string) (unsafe.Pointer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement))
	defer itf.Release()
	v := (*iFrameworkElement)(unsafe.Pointer(itf))
	return v.FindName(name)
}

func (impl *FrameworkElement) SetRequestedTheme(value ElementTheme) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFrameworkElement2))
	defer itf.Release()
	v := (*iFrameworkElement2)(unsafe.Pointer(itf))
	return v.SetRequestedTheme(value)
}

const GUIDiFrameworkElement string = "a391d09b-4a99-4b7c-9d8d-6fa5d01f6fbf"
const SignatureiFrameworkElement string = "{a391d09b-4a99-4b7c-9d8d-6fa5d01f6fbf}"

type iFrameworkElement struct {
	ole.IInspectable
}

type iFrameworkElementVtbl struct {
	ole.IInspectableVtbl

	GetTriggers            uintptr
	GetResources           uintptr
	SetResources           uintptr
	GetTag                 uintptr
	SetTag                 uintptr
	GetLanguage            uintptr
	SetLanguage            uintptr
	GetActualWidth         uintptr
	GetActualHeight        uintptr
	GetWidth               uintptr
	SetWidth               uintptr
	GetHeight              uintptr
	SetHeight              uintptr
	GetMinWidth            uintptr
	SetMinWidth            uintptr
	GetMaxWidth            uintptr
	SetMaxWidth            uintptr
	GetMinHeight           uintptr
	SetMinHeight           uintptr
	GetMaxHeight           uintptr
	SetMaxHeight           uintptr
	GetHorizontalAlignment uintptr
	SetHorizontalAlignment uintptr
	GetVerticalAlignment   uintptr
	SetVerticalAlignment   uintptr
	GetMargin              uintptr
	SetMargin              uintptr
	GetName                uintptr
	SetName                uintptr
	GetBaseUri             uintptr
	GetDataContext         uintptr
	SetDataContext         uintptr
	GetStyle               uintptr
	SetStyle               uintptr
	GetParent              uintptr
	GetFlowDirection       uintptr
	SetFlowDirection       uintptr
	AddLoaded              uintptr
	RemoveLoaded           uintptr
	AddUnloaded            uintptr
	RemoveUnloaded         uintptr
	AddSizeChanged         uintptr
	RemoveSizeChanged      uintptr
	AddLayoutUpdated       uintptr
	RemoveLayoutUpdated    uintptr
	FindName               uintptr
	SetBinding             uintptr
}

func (v *iFrameworkElement) VTable() *iFrameworkElementVtbl {
	return (*iFrameworkElementVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iFrameworkElement) SetWidth(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetWidth,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetHeight(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHeight,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetMinWidth(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMinWidth,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetMinHeight(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMinHeight,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetHorizontalAlignment(value HorizontalAlignment) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHorizontalAlignment,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in HorizontalAlignment
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetVerticalAlignment(value VerticalAlignment) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetVerticalAlignment,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in VerticalAlignment
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetMargin(value Thickness) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMargin,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in Thickness
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) SetName(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetName,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFrameworkElement) FindName(name string) (unsafe.Pointer, error) {
	var out unsafe.Pointer
	nameHStr, err := ole.NewHString(name)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().FindName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(nameHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out unsafe.Pointer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiFrameworkElement2 string = "f19104be-422a-4904-a52f-ee72010429e5"
const SignatureiFrameworkElement2 string = "{f19104be-422a-4904-a52f-ee72010429e5}"

type iFrameworkElement2 struct {
	ole.IInspectable
}

type iFrameworkElement2Vtbl struct {
	ole.IInspectableVtbl

	GetRequestedTheme        uintptr
	SetRequestedTheme        uintptr
	AddDataContextChanged    uintptr
	RemoveDataContextChanged uintptr
	GetBindingExpression     uintptr
}

func (v *iFrameworkElement2) VTable() *iFrameworkElement2Vtbl {
	return (*iFrameworkElement2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iFrameworkElement2) SetRequestedTheme(value ElementTheme) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetRequestedTheme,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ElementTheme
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiFrameworkElement3 string = "c81c2720-5c52-4bbe-a199-2b1e34f00f70"
const SignatureiFrameworkElement3 string = "{c81c2720-5c52-4bbe-a199-2b1e34f00f70}"

type iFrameworkElement3 struct {
	ole.IInspectable
}

type iFrameworkElement3Vtbl struct {
	ole.IInspectableVtbl

	AddLoading    uintptr
	RemoveLoading uintptr
}

func (v *iFrameworkElement3) VTable() *iFrameworkElement3Vtbl {
	return (*iFrameworkElement3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElement4 string = "6b765bb3-fba3-4404-bdee-1a45d1ca5f21"
const SignatureiFrameworkElement4 string = "{6b765bb3-fba3-4404-bdee-1a45d1ca5f21}"

type iFrameworkElement4 struct {
	ole.IInspectable
}

type iFrameworkElement4Vtbl struct {
	ole.IInspectableVtbl

	GetAllowFocusOnInteraction       uintptr
	SetAllowFocusOnInteraction       uintptr
	GetFocusVisualMargin             uintptr
	SetFocusVisualMargin             uintptr
	GetFocusVisualSecondaryThickness uintptr
	SetFocusVisualSecondaryThickness uintptr
	GetFocusVisualPrimaryThickness   uintptr
	SetFocusVisualPrimaryThickness   uintptr
	GetFocusVisualSecondaryBrush     uintptr
	SetFocusVisualSecondaryBrush     uintptr
	GetFocusVisualPrimaryBrush       uintptr
	SetFocusVisualPrimaryBrush       uintptr
	GetAllowFocusWhenDisabled        uintptr
	SetAllowFocusWhenDisabled        uintptr
}

func (v *iFrameworkElement4) VTable() *iFrameworkElement4Vtbl {
	return (*iFrameworkElement4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElement6 string = "792a5d91-62a1-40bf-a0ce-f9c131fcb7a7"
const SignatureiFrameworkElement6 string = "{792a5d91-62a1-40bf-a0ce-f9c131fcb7a7}"

type iFrameworkElement6 struct {
	ole.IInspectable
}

type iFrameworkElement6Vtbl struct {
	ole.IInspectableVtbl

	GetActualTheme           uintptr
	AddActualThemeChanged    uintptr
	RemoveActualThemeChanged uintptr
}

func (v *iFrameworkElement6) VTable() *iFrameworkElement6Vtbl {
	return (*iFrameworkElement6Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElement7 string = "2263886c-c069-570f-b9cc-9e21dd028d8e"
const SignatureiFrameworkElement7 string = "{2263886c-c069-570f-b9cc-9e21dd028d8e}"

type iFrameworkElement7 struct {
	ole.IInspectable
}

type iFrameworkElement7Vtbl struct {
	ole.IInspectableVtbl

	GetIsLoaded                    uintptr
	AddEffectiveViewportChanged    uintptr
	RemoveEffectiveViewportChanged uintptr
}

func (v *iFrameworkElement7) VTable() *iFrameworkElement7Vtbl {
	return (*iFrameworkElement7Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElementProtected7 string = "65aa0480-22e3-5103-ad2a-b626f88ca5ae"
const SignatureiFrameworkElementProtected7 string = "{65aa0480-22e3-5103-ad2a-b626f88ca5ae}"

type iFrameworkElementProtected7 struct {
	ole.IInspectable
}

type iFrameworkElementProtected7Vtbl struct {
	ole.IInspectableVtbl

	InvalidateViewport uintptr
}

func (v *iFrameworkElementProtected7) VTable() *iFrameworkElementProtected7Vtbl {
	return (*iFrameworkElementProtected7Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElementOverrides string = "da007e54-b3c2-4b9a-aa8e-d3f071262b97"
const SignatureiFrameworkElementOverrides string = "{da007e54-b3c2-4b9a-aa8e-d3f071262b97}"

type iFrameworkElementOverrides struct {
	ole.IInspectable
}

type iFrameworkElementOverridesVtbl struct {
	ole.IInspectableVtbl

	MeasureOverride uintptr
	ArrangeOverride uintptr
	OnApplyTemplate uintptr
}

func (v *iFrameworkElementOverrides) VTable() *iFrameworkElementOverridesVtbl {
	return (*iFrameworkElementOverridesVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFrameworkElementOverrides2 string = "cb5cd2b9-e3b4-458c-b64e-1434fd1bd88a"
const SignatureiFrameworkElementOverrides2 string = "{cb5cd2b9-e3b4-458c-b64e-1434fd1bd88a}"

type iFrameworkElementOverrides2 struct {
	ole.IInspectable
}

type iFrameworkElementOverrides2Vtbl struct {
	ole.IInspectableVtbl

	GoToElementStateCore uintptr
}

func (v *iFrameworkElementOverrides2) VTable() *iFrameworkElementOverrides2Vtbl {
	return (*iFrameworkElementOverrides2Vtbl)(unsafe.Pointer(v.RawVTable))
}
