// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type HorizontalAlignment int32

const SignatureHorizontalAlignment string = "enum(Windows.UI.Xaml.HorizontalAlignment;i4)"

const (
	HorizontalAlignmentLeft    HorizontalAlignment = 0
	HorizontalAlignmentCenter  HorizontalAlignment = 1
	HorizontalAlignmentRight   HorizontalAlignment = 2
	HorizontalAlignmentStretch HorizontalAlignment = 3
)
