// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureResourceDictionary string = "rc(Windows.UI.Xaml.ResourceDictionary;{c1ea4f24-d6de-4191-8e3a-f48601f7489c})"

type ResourceDictionary struct {
	ole.IUnknown
}

const GUIDiResourceDictionary string = "c1ea4f24-d6de-4191-8e3a-f48601f7489c"
const SignatureiResourceDictionary string = "{c1ea4f24-d6de-4191-8e3a-f48601f7489c}"

type iResourceDictionary struct {
	ole.IInspectable
}

type iResourceDictionaryVtbl struct {
	ole.IInspectableVtbl

	GetSource             uintptr
	SetSource             uintptr
	GetMergedDictionaries uintptr
	GetThemeDictionaries  uintptr
}

func (v *iResourceDictionary) VTable() *iResourceDictionaryVtbl {
	return (*iResourceDictionaryVtbl)(unsafe.Pointer(v.RawVTable))
}
