// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureRoutedEventArgs string = "rc(Windows.UI.Xaml.RoutedEventArgs;{5c985ac6-d802-4b38-a223-bf070c43fedf})"

type RoutedEventArgs struct {
	ole.IUnknown
}

const GUIDiRoutedEventArgs string = "5c985ac6-d802-4b38-a223-bf070c43fedf"
const SignatureiRoutedEventArgs string = "{5c985ac6-d802-4b38-a223-bf070c43fedf}"

type iRoutedEventArgs struct {
	ole.IInspectable
}

type iRoutedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetOriginalSource uintptr
}

func (v *iRoutedEventArgs) VTable() *iRoutedEventArgsVtbl {
	return (*iRoutedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}
