// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type TextWrapping int32

const SignatureTextWrapping string = "enum(Windows.UI.Xaml.TextWrapping;i4)"

const (
	TextWrappingNoWrap         TextWrapping = 1
	TextWrappingWrap           TextWrapping = 2
	TextWrappingWrapWholeWords TextWrapping = 3
)
