// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

const SignatureThickness string = "struct(Windows.UI.Xaml.Thickness;f8;f8;f8;f8)"

type Thickness struct {
	Left float64

	Top float64

	Right float64

	Bottom float64
}
