// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureUIElement string = "rc(Windows.UI.Xaml.UIElement;{676d0be9-b65c-41c6-ba40-58cf87f201c1})"

type UIElement struct {
	ole.IUnknown
}

func (impl *UIElement) SetOpacity(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiUIElement))
	defer itf.Release()
	v := (*iUIElement)(unsafe.Pointer(itf))
	return v.SetOpacity(value)
}

func (impl *UIElement) SetVisibility(value Visibility) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiUIElement))
	defer itf.Release()
	v := (*iUIElement)(unsafe.Pointer(itf))
	return v.SetVisibility(value)
}

const GUIDiUIElement string = "676d0be9-b65c-41c6-ba40-58cf87f201c1"
const SignatureiUIElement string = "{676d0be9-b65c-41c6-ba40-58cf87f201c1}"

type iUIElement struct {
	ole.IInspectable
}

type iUIElementVtbl struct {
	ole.IInspectableVtbl

	GetDesiredSize                    uintptr
	GetAllowDrop                      uintptr
	SetAllowDrop                      uintptr
	GetOpacity                        uintptr
	SetOpacity                        uintptr
	GetClip                           uintptr
	SetClip                           uintptr
	GetRenderTransform                uintptr
	SetRenderTransform                uintptr
	GetProjection                     uintptr
	SetProjection                     uintptr
	GetRenderTransformOrigin          uintptr
	SetRenderTransformOrigin          uintptr
	GetIsHitTestVisible               uintptr
	SetIsHitTestVisible               uintptr
	GetVisibility                     uintptr
	SetVisibility                     uintptr
	GetRenderSize                     uintptr
	GetUseLayoutRounding              uintptr
	SetUseLayoutRounding              uintptr
	GetTransitions                    uintptr
	SetTransitions                    uintptr
	GetCacheMode                      uintptr
	SetCacheMode                      uintptr
	GetIsTapEnabled                   uintptr
	SetIsTapEnabled                   uintptr
	GetIsDoubleTapEnabled             uintptr
	SetIsDoubleTapEnabled             uintptr
	GetIsRightTapEnabled              uintptr
	SetIsRightTapEnabled              uintptr
	GetIsHoldingEnabled               uintptr
	SetIsHoldingEnabled               uintptr
	GetManipulationMode               uintptr
	SetManipulationMode               uintptr
	GetPointerCaptures                uintptr
	AddKeyUp                          uintptr
	RemoveKeyUp                       uintptr
	AddKeyDown                        uintptr
	RemoveKeyDown                     uintptr
	AddGotFocus                       uintptr
	RemoveGotFocus                    uintptr
	AddLostFocus                      uintptr
	RemoveLostFocus                   uintptr
	AddDragEnter                      uintptr
	RemoveDragEnter                   uintptr
	AddDragLeave                      uintptr
	RemoveDragLeave                   uintptr
	AddDragOver                       uintptr
	RemoveDragOver                    uintptr
	AddDrop                           uintptr
	RemoveDrop                        uintptr
	AddPointerPressed                 uintptr
	RemovePointerPressed              uintptr
	AddPointerMoved                   uintptr
	RemovePointerMoved                uintptr
	AddPointerReleased                uintptr
	RemovePointerReleased             uintptr
	AddPointerEntered                 uintptr
	RemovePointerEntered              uintptr
	AddPointerExited                  uintptr
	RemovePointerExited               uintptr
	AddPointerCaptureLost             uintptr
	RemovePointerCaptureLost          uintptr
	AddPointerCanceled                uintptr
	RemovePointerCanceled             uintptr
	AddPointerWheelChanged            uintptr
	RemovePointerWheelChanged         uintptr
	AddTapped                         uintptr
	RemoveTapped                      uintptr
	AddDoubleTapped                   uintptr
	RemoveDoubleTapped                uintptr
	AddHolding                        uintptr
	RemoveHolding                     uintptr
	AddRightTapped                    uintptr
	RemoveRightTapped                 uintptr
	AddManipulationStarting           uintptr
	RemoveManipulationStarting        uintptr
	AddManipulationInertiaStarting    uintptr
	RemoveManipulationInertiaStarting uintptr
	AddManipulationStarted            uintptr
	RemoveManipulationStarted         uintptr
	AddManipulationDelta              uintptr
	RemoveManipulationDelta           uintptr
	AddManipulationCompleted          uintptr
	RemoveManipulationCompleted       uintptr
	Measure                           uintptr
	Arrange                           uintptr
	CapturePointer                    uintptr
	ReleasePointerCapture             uintptr
	ReleasePointerCaptures            uintptr
	AddHandler                        uintptr
	RemoveHandler                     uintptr
	TransformToVisual                 uintptr
	InvalidateMeasure                 uintptr
	InvalidateArrange                 uintptr
	UpdateLayout                      uintptr
}

func (v *iUIElement) VTable() *iUIElementVtbl {
	return (*iUIElementVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iUIElement) SetOpacity(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOpacity,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iUIElement) SetVisibility(value Visibility) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetVisibility,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in Visibility
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiUIElement2 string = "676d0bf9-b66c-41d6-ba50-58cf87f201d1"
const SignatureiUIElement2 string = "{676d0bf9-b66c-41d6-ba50-58cf87f201d1}"

type iUIElement2 struct {
	ole.IInspectable
}

type iUIElement2Vtbl struct {
	ole.IInspectableVtbl

	GetCompositeMode          uintptr
	SetCompositeMode          uintptr
	CancelDirectManipulations uintptr
}

func (v *iUIElement2) VTable() *iUIElement2Vtbl {
	return (*iUIElement2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement3 string = "bc2b28f1-26f2-4aab-b256-3b5350881e37"
const SignatureiUIElement3 string = "{bc2b28f1-26f2-4aab-b256-3b5350881e37}"

type iUIElement3 struct {
	ole.IInspectable
}

type iUIElement3Vtbl struct {
	ole.IInspectableVtbl

	GetTransform3D      uintptr
	SetTransform3D      uintptr
	GetCanDrag          uintptr
	SetCanDrag          uintptr
	AddDragStarting     uintptr
	RemoveDragStarting  uintptr
	AddDropCompleted    uintptr
	RemoveDropCompleted uintptr
	StartDragAsync      uintptr
}

func (v *iUIElement3) VTable() *iUIElement3Vtbl {
	return (*iUIElement3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement4 string = "69145cd4-199a-4657-9e57-e99e8f136712"
const SignatureiUIElement4 string = "{69145cd4-199a-4657-9e57-e99e8f136712}"

type iUIElement4 struct {
	ole.IInspectable
}

type iUIElement4Vtbl struct {
	ole.IInspectableVtbl

	GetContextFlyout                     uintptr
	SetContextFlyout                     uintptr
	GetExitDisplayModeOnAccessKeyInvoked uintptr
	SetExitDisplayModeOnAccessKeyInvoked uintptr
	GetIsAccessKeyScope                  uintptr
	SetIsAccessKeyScope                  uintptr
	GetAccessKeyScopeOwner               uintptr
	SetAccessKeyScopeOwner               uintptr
	GetAccessKey                         uintptr
	SetAccessKey                         uintptr
	AddContextRequested                  uintptr
	RemoveContextRequested               uintptr
	AddContextCanceled                   uintptr
	RemoveContextCanceled                uintptr
	AddAccessKeyDisplayRequested         uintptr
	RemoveAccessKeyDisplayRequested      uintptr
	AddAccessKeyDisplayDismissed         uintptr
	RemoveAccessKeyDisplayDismissed      uintptr
	AddAccessKeyInvoked                  uintptr
	RemoveAccessKeyInvoked               uintptr
}

func (v *iUIElement4) VTable() *iUIElement4Vtbl {
	return (*iUIElement4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement5 string = "8eed9bc2-a58c-4453-af0f-a92ee06d0317"
const SignatureiUIElement5 string = "{8eed9bc2-a58c-4453-af0f-a92ee06d0317}"

type iUIElement5 struct {
	ole.IInspectable
}

type iUIElement5Vtbl struct {
	ole.IInspectableVtbl

	GetLights                         uintptr
	GetKeyTipPlacementMode            uintptr
	SetKeyTipPlacementMode            uintptr
	GetKeyTipHorizontalOffset         uintptr
	SetKeyTipHorizontalOffset         uintptr
	GetKeyTipVerticalOffset           uintptr
	SetKeyTipVerticalOffset           uintptr
	GetXYFocusKeyboardNavigation      uintptr
	SetXYFocusKeyboardNavigation      uintptr
	GetXYFocusUpNavigationStrategy    uintptr
	SetXYFocusUpNavigationStrategy    uintptr
	GetXYFocusDownNavigationStrategy  uintptr
	SetXYFocusDownNavigationStrategy  uintptr
	GetXYFocusLeftNavigationStrategy  uintptr
	SetXYFocusLeftNavigationStrategy  uintptr
	GetXYFocusRightNavigationStrategy uintptr
	SetXYFocusRightNavigationStrategy uintptr
	GetHighContrastAdjustment         uintptr
	SetHighContrastAdjustment         uintptr
	GetTabFocusNavigation             uintptr
	SetTabFocusNavigation             uintptr
	AddGettingFocus                   uintptr
	RemoveGettingFocus                uintptr
	AddLosingFocus                    uintptr
	RemoveLosingFocus                 uintptr
	AddNoFocusCandidateFound          uintptr
	RemoveNoFocusCandidateFound       uintptr
	StartBringIntoView                uintptr
	StartBringIntoViewWithOptions     uintptr
}

func (v *iUIElement5) VTable() *iUIElement5Vtbl {
	return (*iUIElement5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement7 string = "cafc4968-6369-4249-80f9-3d656319e811"
const SignatureiUIElement7 string = "{cafc4968-6369-4249-80f9-3d656319e811}"

type iUIElement7 struct {
	ole.IInspectable
}

type iUIElement7Vtbl struct {
	ole.IInspectableVtbl

	GetKeyboardAccelerators           uintptr
	AddCharacterReceived              uintptr
	RemoveCharacterReceived           uintptr
	AddProcessKeyboardAccelerators    uintptr
	RemoveProcessKeyboardAccelerators uintptr
	AddPreviewKeyDown                 uintptr
	RemovePreviewKeyDown              uintptr
	AddPreviewKeyUp                   uintptr
	RemovePreviewKeyUp                uintptr
	TryInvokeKeyboardAccelerator      uintptr
}

func (v *iUIElement7) VTable() *iUIElement7Vtbl {
	return (*iUIElement7Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement8 string = "3ab70e85-d508-4477-b6f8-0e435701c836"
const SignatureiUIElement8 string = "{3ab70e85-d508-4477-b6f8-0e435701c836}"

type iUIElement8 struct {
	ole.IInspectable
}

type iUIElement8Vtbl struct {
	ole.IInspectableVtbl

	GetKeyTipTarget                       uintptr
	SetKeyTipTarget                       uintptr
	GetKeyboardAcceleratorPlacementTarget uintptr
	SetKeyboardAcceleratorPlacementTarget uintptr
	GetKeyboardAcceleratorPlacementMode   uintptr
	SetKeyboardAcceleratorPlacementMode   uintptr
	AddBringIntoViewRequested             uintptr
	RemoveBringIntoViewRequested          uintptr
}

func (v *iUIElement8) VTable() *iUIElement8Vtbl {
	return (*iUIElement8Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement9 string = "b4a04776-4e88-50ca-8f2b-08940d6c5f94"
const SignatureiUIElement9 string = "{b4a04776-4e88-50ca-8f2b-08940d6c5f94}"

type iUIElement9 struct {
	ole.IInspectable
}

type iUIElement9Vtbl struct {
	ole.IInspectableVtbl

	GetCanBeScrollAnchor     uintptr
	SetCanBeScrollAnchor     uintptr
	GetOpacityTransition     uintptr
	SetOpacityTransition     uintptr
	GetTranslation           uintptr
	SetTranslation           uintptr
	GetTranslationTransition uintptr
	SetTranslationTransition uintptr
	GetRotation              uintptr
	SetRotation              uintptr
	GetRotationTransition    uintptr
	SetRotationTransition    uintptr
	GetScale                 uintptr
	SetScale                 uintptr
	GetScaleTransition       uintptr
	SetScaleTransition       uintptr
	GetTransformMatrix       uintptr
	SetTransformMatrix       uintptr
	GetCenterPoint           uintptr
	SetCenterPoint           uintptr
	GetRotationAxis          uintptr
	SetRotationAxis          uintptr
	StartAnimation           uintptr
	StopAnimation            uintptr
}

func (v *iUIElement9) VTable() *iUIElement9Vtbl {
	return (*iUIElement9Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElement10 string = "d531c629-ad2c-5f6b-adcf-fb87287d18d7"
const SignatureiUIElement10 string = "{d531c629-ad2c-5f6b-adcf-fb87287d18d7}"

type iUIElement10 struct {
	ole.IInspectable
}

type iUIElement10Vtbl struct {
	ole.IInspectableVtbl

	GetActualOffset uintptr
	GetActualSize   uintptr
	GetXamlRoot     uintptr
	SetXamlRoot     uintptr
	GetUIContext    uintptr
	GetShadow       uintptr
	SetShadow       uintptr
}

func (v *iUIElement10) VTable() *iUIElement10Vtbl {
	return (*iUIElement10Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElementOverrides string = "608d2f1d-7858-4aeb-89e4-b54e2c7ed3d3"
const SignatureiUIElementOverrides string = "{608d2f1d-7858-4aeb-89e4-b54e2c7ed3d3}"

type iUIElementOverrides struct {
	ole.IInspectable
}

type iUIElementOverridesVtbl struct {
	ole.IInspectableVtbl

	OnCreateAutomationPeer           uintptr
	OnDisconnectVisualChildren       uintptr
	FindSubElementsForTouchTargeting uintptr
}

func (v *iUIElementOverrides) VTable() *iUIElementOverridesVtbl {
	return (*iUIElementOverridesVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElementOverrides7 string = "b97f7f68-c29b-4c99-a1c3-952619d6e720"
const SignatureiUIElementOverrides7 string = "{b97f7f68-c29b-4c99-a1c3-952619d6e720}"

type iUIElementOverrides7 struct {
	ole.IInspectable
}

type iUIElementOverrides7Vtbl struct {
	ole.IInspectableVtbl

	GetChildrenInTabFocusOrder    uintptr
	OnProcessKeyboardAccelerators uintptr
}

func (v *iUIElementOverrides7) VTable() *iUIElementOverrides7Vtbl {
	return (*iUIElementOverrides7Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElementOverrides8 string = "4a5a645c-548d-48cf-b998-7844d6e235a1"
const SignatureiUIElementOverrides8 string = "{4a5a645c-548d-48cf-b998-7844d6e235a1}"

type iUIElementOverrides8 struct {
	ole.IInspectable
}

type iUIElementOverrides8Vtbl struct {
	ole.IInspectableVtbl

	OnKeyboardAcceleratorInvoked uintptr
	OnBringIntoViewRequested     uintptr
}

func (v *iUIElementOverrides8) VTable() *iUIElementOverrides8Vtbl {
	return (*iUIElementOverrides8Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUIElementOverrides9 string = "9a6e5973-6d63-54f2-90fa-62813b20b7b9"
const SignatureiUIElementOverrides9 string = "{9a6e5973-6d63-54f2-90fa-62813b20b7b9}"

type iUIElementOverrides9 struct {
	ole.IInspectable
}

type iUIElementOverrides9Vtbl struct {
	ole.IInspectableVtbl

	PopulatePropertyInfoOverride uintptr
}

func (v *iUIElementOverrides9) VTable() *iUIElementOverrides9Vtbl {
	return (*iUIElementOverrides9Vtbl)(unsafe.Pointer(v.RawVTable))
}
