// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type VerticalAlignment int32

const SignatureVerticalAlignment string = "enum(Windows.UI.Xaml.VerticalAlignment;i4)"

const (
	VerticalAlignmentTop     VerticalAlignment = 0
	VerticalAlignmentCenter  VerticalAlignment = 1
	VerticalAlignmentBottom  VerticalAlignment = 2
	VerticalAlignmentStretch VerticalAlignment = 3
)
