// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package xaml

type Visibility int32

const SignatureVisibility string = "enum(Windows.UI.Xaml.Visibility;i4)"

const (
	VisibilityVisible   Visibility = 0
	VisibilityCollapsed Visibility = 1
)
