// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDiPropertyValueStatics string = "629bdbc8-d932-4ff4-96b9-8d96c5c1e858"
const SignatureiPropertyValueStatics string = "{629bdbc8-d932-4ff4-96b9-8d96c5c1e858}"

type iPropertyValueStatics struct {
	ole.IInspectable
}

type iPropertyValueStaticsVtbl struct {
	ole.IInspectableVtbl

	PropertyValueCreateEmpty            uintptr
	PropertyValueCreateUInt8            uintptr
	PropertyValueCreateInt16            uintptr
	PropertyValueCreateUInt16           uintptr
	PropertyValueCreateInt32            uintptr
	PropertyValueCreateUInt32           uintptr
	PropertyValueCreateInt64            uintptr
	PropertyValueCreateUInt64           uintptr
	PropertyValueCreateSingle           uintptr
	PropertyValueCreateDouble           uintptr
	PropertyValueCreateChar16           uintptr
	PropertyValueCreateBoolean          uintptr
	PropertyValueCreateString           uintptr
	PropertyValueCreateInspectable      uintptr
	PropertyValueCreateGuid             uintptr
	PropertyValueCreateDateTime         uintptr
	PropertyValueCreateTimeSpan         uintptr
	PropertyValueCreatePoint            uintptr
	PropertyValueCreateSize             uintptr
	PropertyValueCreateRect             uintptr
	PropertyValueCreateUInt8Array       uintptr
	PropertyValueCreateInt16Array       uintptr
	PropertyValueCreateUInt16Array      uintptr
	PropertyValueCreateInt32Array       uintptr
	PropertyValueCreateUInt32Array      uintptr
	PropertyValueCreateInt64Array       uintptr
	PropertyValueCreateUInt64Array      uintptr
	PropertyValueCreateSingleArray      uintptr
	PropertyValueCreateDoubleArray      uintptr
	PropertyValueCreateChar16Array      uintptr
	PropertyValueCreateBooleanArray     uintptr
	PropertyValueCreateStringArray      uintptr
	PropertyValueCreateInspectableArray uintptr
	PropertyValueCreateGuidArray        uintptr
	PropertyValueCreateDateTimeArray    uintptr
	PropertyValueCreateTimeSpanArray    uintptr
	PropertyValueCreatePointArray       uintptr
	PropertyValueCreateSizeArray        uintptr
	PropertyValueCreateRectArray        uintptr
}

func (v *iPropertyValueStatics) VTable() *iPropertyValueStaticsVtbl {
	return (*iPropertyValueStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func PropertyValueCreateString(value string) (unsafe.Pointer, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Foundation.PropertyValue", ole.NewGUID(GUIDiPropertyValueStatics))
	if err != nil {
		return nil, err
	}
	v := (*iPropertyValueStatics)(unsafe.Pointer(inspectable))

	var out unsafe.Pointer
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().PropertyValueCreateString,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(valueHStr),            // in string
		uintptr(unsafe.Pointer(&out)), // out unsafe.Pointer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
