// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureUri string = "rc(Windows.Foundation.Uri;{9e365e57-48b2-4160-956f-c7385120bbfc})"

type Uri struct {
	ole.IUnknown
}

const GUIDiUriRuntimeClass string = "9e365e57-48b2-4160-956f-c7385120bbfc"
const SignatureiUriRuntimeClass string = "{9e365e57-48b2-4160-956f-c7385120bbfc}"

type iUriRuntimeClass struct {
	ole.IInspectable
}

type iUriRuntimeClassVtbl struct {
	ole.IInspectableVtbl

	GetAbsoluteUri uintptr
	GetDisplayUri  uintptr
	GetDomain      uintptr
	GetExtension   uintptr
	GetFragment    uintptr
	GetHost        uintptr
	GetPassword    uintptr
	GetPath        uintptr
	GetQuery       uintptr
	GetQueryParsed uintptr
	GetRawUri      uintptr
	GetSchemeName  uintptr
	GetUserName    uintptr
	GetPort        uintptr
	GetSuspicious  uintptr
	Equals         uintptr
	CombineUri     uintptr
}

func (v *iUriRuntimeClass) VTable() *iUriRuntimeClassVtbl {
	return (*iUriRuntimeClassVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUriRuntimeClassWithAbsoluteCanonicalUri string = "758d9661-221c-480f-a339-50656673f46f"
const SignatureiUriRuntimeClassWithAbsoluteCanonicalUri string = "{758d9661-221c-480f-a339-50656673f46f}"

type iUriRuntimeClassWithAbsoluteCanonicalUri struct {
	ole.IInspectable
}

type iUriRuntimeClassWithAbsoluteCanonicalUriVtbl struct {
	ole.IInspectableVtbl

	GetAbsoluteCanonicalUri uintptr
	GetDisplayIri           uintptr
}

func (v *iUriRuntimeClassWithAbsoluteCanonicalUri) VTable() *iUriRuntimeClassWithAbsoluteCanonicalUriVtbl {
	return (*iUriRuntimeClassWithAbsoluteCanonicalUriVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiUriRuntimeClassFactory string = "44a9796f-723e-4fdf-a218-033e75b0c084"
const SignatureiUriRuntimeClassFactory string = "{44a9796f-723e-4fdf-a218-033e75b0c084}"

type iUriRuntimeClassFactory struct {
	ole.IInspectable
}

type iUriRuntimeClassFactoryVtbl struct {
	ole.IInspectableVtbl

	UriCreateUri             uintptr
	UriCreateWithRelativeUri uintptr
}

func (v *iUriRuntimeClassFactory) VTable() *iUriRuntimeClassFactoryVtbl {
	return (*iUriRuntimeClassFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func UriCreateUri(uri string) (*Uri, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Foundation.Uri", ole.NewGUID(GUIDiUriRuntimeClassFactory))
	if err != nil {
		return nil, err
	}
	v := (*iUriRuntimeClassFactory)(unsafe.Pointer(inspectable))

	var out *Uri
	uriHStr, err := ole.NewHString(uri)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().UriCreateUri,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(uriHStr),              // in string
		uintptr(unsafe.Pointer(&out)), // out Uri
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
