// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package playback

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureMediaPlaybackSession string = "rc(Windows.Media.Playback.MediaPlaybackSession;{c32b683d-0407-41ba-8946-8b345a5a5435})"

type MediaPlaybackSession struct {
	ole.IUnknown
}

func (impl *MediaPlaybackSession) GetPosition() (foundation.TimeSpan, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlaybackSession))
	defer itf.Release()
	v := (*iMediaPlaybackSession)(unsafe.Pointer(itf))
	return v.GetPosition()
}

func (impl *MediaPlaybackSession) SetPosition(value foundation.TimeSpan) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlaybackSession))
	defer itf.Release()
	v := (*iMediaPlaybackSession)(unsafe.Pointer(itf))
	return v.SetPosition(value)
}

func (impl *MediaPlaybackSession) GetNaturalVideoHeight() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlaybackSession))
	defer itf.Release()
	v := (*iMediaPlaybackSession)(unsafe.Pointer(itf))
	return v.GetNaturalVideoHeight()
}

func (impl *MediaPlaybackSession) GetNaturalVideoWidth() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlaybackSession))
	defer itf.Release()
	v := (*iMediaPlaybackSession)(unsafe.Pointer(itf))
	return v.GetNaturalVideoWidth()
}

const GUIDiMediaPlaybackSession string = "c32b683d-0407-41ba-8946-8b345a5a5435"
const SignatureiMediaPlaybackSession string = "{c32b683d-0407-41ba-8946-8b345a5a5435}"

type iMediaPlaybackSession struct {
	ole.IInspectable
}

type iMediaPlaybackSessionVtbl struct {
	ole.IInspectableVtbl

	AddPlaybackStateChanged         uintptr
	RemovePlaybackStateChanged      uintptr
	AddPlaybackRateChanged          uintptr
	RemovePlaybackRateChanged       uintptr
	AddSeekCompleted                uintptr
	RemoveSeekCompleted             uintptr
	AddBufferingStarted             uintptr
	RemoveBufferingStarted          uintptr
	AddBufferingEnded               uintptr
	RemoveBufferingEnded            uintptr
	AddBufferingProgressChanged     uintptr
	RemoveBufferingProgressChanged  uintptr
	AddDownloadProgressChanged      uintptr
	RemoveDownloadProgressChanged   uintptr
	AddNaturalDurationChanged       uintptr
	RemoveNaturalDurationChanged    uintptr
	AddPositionChanged              uintptr
	RemovePositionChanged           uintptr
	AddNaturalVideoSizeChanged      uintptr
	RemoveNaturalVideoSizeChanged   uintptr
	GetMediaPlayer                  uintptr
	GetNaturalDuration              uintptr
	GetPosition                     uintptr
	SetPosition                     uintptr
	GetPlaybackState                uintptr
	GetCanSeek                      uintptr
	GetCanPause                     uintptr
	GetIsProtected                  uintptr
	GetPlaybackRate                 uintptr
	SetPlaybackRate                 uintptr
	GetBufferingProgress            uintptr
	GetDownloadProgress             uintptr
	GetNaturalVideoHeight           uintptr
	GetNaturalVideoWidth            uintptr
	GetNormalizedSourceRect         uintptr
	SetNormalizedSourceRect         uintptr
	GetStereoscopicVideoPackingMode uintptr
	SetStereoscopicVideoPackingMode uintptr
}

func (v *iMediaPlaybackSession) VTable() *iMediaPlaybackSessionVtbl {
	return (*iMediaPlaybackSessionVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iMediaPlaybackSession) GetPosition() (foundation.TimeSpan, error) {
	var out foundation.TimeSpan
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPosition,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.TimeSpan
	)

	if hr != 0 {
		return foundation.TimeSpan{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iMediaPlaybackSession) SetPosition(value foundation.TimeSpan) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPosition,
		uintptr(unsafe.Pointer(v)),                  // this
		uintptr(*(*uint64)(unsafe.Pointer(&value))), // in foundation.TimeSpan
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iMediaPlaybackSession) GetNaturalVideoHeight() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNaturalVideoHeight,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iMediaPlaybackSession) GetNaturalVideoWidth() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNaturalVideoWidth,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiMediaPlaybackSession2 string = "f8ba7c79-1fc8-4097-ad70-c0fa18cc0050"
const SignatureiMediaPlaybackSession2 string = "{f8ba7c79-1fc8-4097-ad70-c0fa18cc0050}"

type iMediaPlaybackSession2 struct {
	ole.IInspectable
}

type iMediaPlaybackSession2Vtbl struct {
	ole.IInspectableVtbl

	AddBufferedRangesChanged            uintptr
	RemoveBufferedRangesChanged         uintptr
	AddPlayedRangesChanged              uintptr
	RemovePlayedRangesChanged           uintptr
	AddSeekableRangesChanged            uintptr
	RemoveSeekableRangesChanged         uintptr
	AddSupportedPlaybackRatesChanged    uintptr
	RemoveSupportedPlaybackRatesChanged uintptr
	GetSphericalVideoProjection         uintptr
	GetIsMirroring                      uintptr
	SetIsMirroring                      uintptr
	GetBufferedRanges                   uintptr
	GetPlayedRanges                     uintptr
	GetSeekableRanges                   uintptr
	IsSupportedPlaybackRateRange        uintptr
}

func (v *iMediaPlaybackSession2) VTable() *iMediaPlaybackSession2Vtbl {
	return (*iMediaPlaybackSession2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiMediaPlaybackSession3 string = "7ba2b41a-a3e2-405f-b77b-a4812c238b66"
const SignatureiMediaPlaybackSession3 string = "{7ba2b41a-a3e2-405f-b77b-a4812c238b66}"

type iMediaPlaybackSession3 struct {
	ole.IInspectable
}

type iMediaPlaybackSession3Vtbl struct {
	ole.IInspectableVtbl

	GetPlaybackRotation             uintptr
	SetPlaybackRotation             uintptr
	GetOutputDegradationPolicyState uintptr
}

func (v *iMediaPlaybackSession3) VTable() *iMediaPlaybackSession3Vtbl {
	return (*iMediaPlaybackSession3Vtbl)(unsafe.Pointer(v.RawVTable))
}
