// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureBorder string = "rc(Windows.UI.Xaml.Controls.Border;{797c4539-45bd-4633-a044-bfb02ef5170f})"

type Border struct {
	ole.IUnknown
}

func NewBorder() (*Border, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Controls.Border")
	if err != nil {
		return nil, err
	}
	return (*Border)(unsafe.Pointer(inspectable)), nil
}

func (impl *Border) SetBackground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBorder))
	defer itf.Release()
	v := (*iBorder)(unsafe.Pointer(itf))
	return v.SetBackground(value)
}

func (impl *Border) SetCornerRadius(value xaml.CornerRadius) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBorder))
	defer itf.Release()
	v := (*iBorder)(unsafe.Pointer(itf))
	return v.SetCornerRadius(value)
}

func (impl *Border) SetPadding(value xaml.Thickness) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBorder))
	defer itf.Release()
	v := (*iBorder)(unsafe.Pointer(itf))
	return v.SetPadding(value)
}

func (impl *Border) SetChild(value *xaml.UIElement) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBorder))
	defer itf.Release()
	v := (*iBorder)(unsafe.Pointer(itf))
	return v.SetChild(value)
}

const GUIDiBorder string = "797c4539-45bd-4633-a044-bfb02ef5170f"
const SignatureiBorder string = "{797c4539-45bd-4633-a044-bfb02ef5170f}"

type iBorder struct {
	ole.IInspectable
}

type iBorderVtbl struct {
	ole.IInspectableVtbl

	GetBorderBrush      uintptr
	SetBorderBrush      uintptr
	GetBorderThickness  uintptr
	SetBorderThickness  uintptr
	GetBackground       uintptr
	SetBackground       uintptr
	GetCornerRadius     uintptr
	SetCornerRadius     uintptr
	GetPadding          uintptr
	SetPadding          uintptr
	GetChild            uintptr
	SetChild            uintptr
	GetChildTransitions uintptr
	SetChildTransitions uintptr
}

func (v *iBorder) VTable() *iBorderVtbl {
	return (*iBorderVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBorder) SetBackground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetBackground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iBorder) SetCornerRadius(value xaml.CornerRadius) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetCornerRadius,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in xaml.CornerRadius
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iBorder) SetPadding(value xaml.Thickness) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPadding,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in xaml.Thickness
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iBorder) SetChild(value *xaml.UIElement) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetChild,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in xaml.UIElement
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiBorder2 string = "a1efbd9d-cb8b-56b5-878d-3a7f43bc9730"
const SignatureiBorder2 string = "{a1efbd9d-cb8b-56b5-878d-3a7f43bc9730}"

type iBorder2 struct {
	ole.IInspectable
}

type iBorder2Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundSizing     uintptr
	SetBackgroundSizing     uintptr
	GetBackgroundTransition uintptr
	SetBackgroundTransition uintptr
}

func (v *iBorder2) VTable() *iBorder2Vtbl {
	return (*iBorder2Vtbl)(unsafe.Pointer(v.RawVTable))
}
