// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureButton string = "rc(Windows.UI.Xaml.Controls.Button;{280335ae-5570-46c7-8e0b-602be71229a2})"

type Button struct {
	ole.IUnknown
}

const GUIDiButton string = "280335ae-5570-46c7-8e0b-602be71229a2"
const SignatureiButton string = "{280335ae-5570-46c7-8e0b-602be71229a2}"

type iButton struct {
	ole.IInspectable
}

type iButtonVtbl struct {
	ole.IInspectableVtbl
}

func (v *iButton) VTable() *iButtonVtbl {
	return (*iButtonVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiButtonWithFlyout string = "09108f87-df6c-4180-9b3a-e60845825811"
const SignatureiButtonWithFlyout string = "{09108f87-df6c-4180-9b3a-e60845825811}"

type iButtonWithFlyout struct {
	ole.IInspectable
}

type iButtonWithFlyoutVtbl struct {
	ole.IInspectableVtbl

	GetFlyout uintptr
	SetFlyout uintptr
}

func (v *iButtonWithFlyout) VTable() *iButtonWithFlyoutVtbl {
	return (*iButtonWithFlyoutVtbl)(unsafe.Pointer(v.RawVTable))
}
