// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureControl string = "rc(Windows.UI.Xaml.Controls.Control;{a8912263-2951-4f58-a9c5-5a134eaa7f07})"

type Control struct {
	ole.IUnknown
}

func (impl *Control) SetFontSize(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetFontSize(value)
}

func (impl *Control) SetForeground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetForeground(value)
}

func (impl *Control) SetIsEnabled(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetIsEnabled(value)
}

func (impl *Control) SetPadding(value xaml.Thickness) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetPadding(value)
}

func (impl *Control) SetBackground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetBackground(value)
}

func (impl *Control) SetBorderThickness(value xaml.Thickness) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetBorderThickness(value)
}

func (impl *Control) GetBorderBrush() (*media.Brush, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.GetBorderBrush()
}

func (impl *Control) SetBorderBrush(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.SetBorderBrush(value)
}

func (impl *Control) Focus(value xaml.FocusState) (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl))
	defer itf.Release()
	v := (*iControl)(unsafe.Pointer(itf))
	return v.Focus(value)
}

func (impl *Control) SetCornerRadius(value xaml.CornerRadius) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiControl7))
	defer itf.Release()
	v := (*iControl7)(unsafe.Pointer(itf))
	return v.SetCornerRadius(value)
}

const GUIDiControl string = "a8912263-2951-4f58-a9c5-5a134eaa7f07"
const SignatureiControl string = "{a8912263-2951-4f58-a9c5-5a134eaa7f07}"

type iControl struct {
	ole.IInspectable
}

type iControlVtbl struct {
	ole.IInspectableVtbl

	GetFontSize                   uintptr
	SetFontSize                   uintptr
	GetFontFamily                 uintptr
	SetFontFamily                 uintptr
	GetFontWeight                 uintptr
	SetFontWeight                 uintptr
	GetFontStyle                  uintptr
	SetFontStyle                  uintptr
	GetFontStretch                uintptr
	SetFontStretch                uintptr
	GetCharacterSpacing           uintptr
	SetCharacterSpacing           uintptr
	GetForeground                 uintptr
	SetForeground                 uintptr
	GetIsTabStop                  uintptr
	SetIsTabStop                  uintptr
	GetIsEnabled                  uintptr
	SetIsEnabled                  uintptr
	GetTabIndex                   uintptr
	SetTabIndex                   uintptr
	GetTabNavigation              uintptr
	SetTabNavigation              uintptr
	GetTemplate                   uintptr
	SetTemplate                   uintptr
	GetPadding                    uintptr
	SetPadding                    uintptr
	GetHorizontalContentAlignment uintptr
	SetHorizontalContentAlignment uintptr
	GetVerticalContentAlignment   uintptr
	SetVerticalContentAlignment   uintptr
	GetBackground                 uintptr
	SetBackground                 uintptr
	GetBorderThickness            uintptr
	SetBorderThickness            uintptr
	GetBorderBrush                uintptr
	SetBorderBrush                uintptr
	GetFocusState                 uintptr
	AddIsEnabledChanged           uintptr
	RemoveIsEnabledChanged        uintptr
	ApplyTemplate                 uintptr
	Focus                         uintptr
}

func (v *iControl) VTable() *iControlVtbl {
	return (*iControlVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iControl) SetFontSize(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetFontSize,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) SetForeground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetForeground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) SetIsEnabled(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetIsEnabled,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) SetPadding(value xaml.Thickness) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPadding,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in xaml.Thickness
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) SetBackground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetBackground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) SetBorderThickness(value xaml.Thickness) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetBorderThickness,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in xaml.Thickness
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) GetBorderBrush() (*media.Brush, error) {
	var out *media.Brush
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetBorderBrush,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out media.Brush
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iControl) SetBorderBrush(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetBorderBrush,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iControl) Focus(value xaml.FocusState) (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().Focus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(value),                // in xaml.FocusState
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiControl2 string = "43e0fe10-14ec-427e-8c57-dee60df60aa8"
const SignatureiControl2 string = "{43e0fe10-14ec-427e-8c57-dee60df60aa8}"

type iControl2 struct {
	ole.IInspectable
}

type iControl2Vtbl struct {
	ole.IInspectableVtbl

	GetIsTextScaleFactorEnabled uintptr
	SetIsTextScaleFactorEnabled uintptr
}

func (v *iControl2) VTable() *iControl2Vtbl {
	return (*iControl2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControl3 string = "077b29e4-dade-4f55-9b96-09e21b28eb1c"
const SignatureiControl3 string = "{077b29e4-dade-4f55-9b96-09e21b28eb1c}"

type iControl3 struct {
	ole.IInspectable
}

type iControl3Vtbl struct {
	ole.IInspectableVtbl

	GetUseSystemFocusVisuals uintptr
	SetUseSystemFocusVisuals uintptr
}

func (v *iControl3) VTable() *iControl3Vtbl {
	return (*iControl3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControl4 string = "0e18aeee-5f2e-44ea-8513-d3875c0a7513"
const SignatureiControl4 string = "{0e18aeee-5f2e-44ea-8513-d3875c0a7513}"

type iControl4 struct {
	ole.IInspectable
}

type iControl4Vtbl struct {
	ole.IInspectableVtbl

	GetIsFocusEngagementEnabled uintptr
	SetIsFocusEngagementEnabled uintptr
	GetIsFocusEngaged           uintptr
	SetIsFocusEngaged           uintptr
	GetRequiresPointer          uintptr
	SetRequiresPointer          uintptr
	GetXYFocusLeft              uintptr
	SetXYFocusLeft              uintptr
	GetXYFocusRight             uintptr
	SetXYFocusRight             uintptr
	GetXYFocusUp                uintptr
	SetXYFocusUp                uintptr
	GetXYFocusDown              uintptr
	SetXYFocusDown              uintptr
	GetElementSoundMode         uintptr
	SetElementSoundMode         uintptr
	AddFocusEngaged             uintptr
	RemoveFocusEngaged          uintptr
	AddFocusDisengaged          uintptr
	RemoveFocusDisengaged       uintptr
	RemoveFocusEngagement       uintptr
}

func (v *iControl4) VTable() *iControl4Vtbl {
	return (*iControl4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControl5 string = "5ebb51d5-9e58-49b7-bc2d-0155ff118664"
const SignatureiControl5 string = "{5ebb51d5-9e58-49b7-bc2d-0155ff118664}"

type iControl5 struct {
	ole.IInspectable
}

type iControl5Vtbl struct {
	ole.IInspectableVtbl

	GetDefaultStyleResourceUri uintptr
	SetDefaultStyleResourceUri uintptr
}

func (v *iControl5) VTable() *iControl5Vtbl {
	return (*iControl5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControl7 string = "3550dbe1-e561-5934-a3ef-7db8bf6e3b45"
const SignatureiControl7 string = "{3550dbe1-e561-5934-a3ef-7db8bf6e3b45}"

type iControl7 struct {
	ole.IInspectable
}

type iControl7Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundSizing uintptr
	SetBackgroundSizing uintptr
	GetCornerRadius     uintptr
	SetCornerRadius     uintptr
}

func (v *iControl7) VTable() *iControl7Vtbl {
	return (*iControl7Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iControl7) SetCornerRadius(value xaml.CornerRadius) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetCornerRadius,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in xaml.CornerRadius
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiControlProtected string = "1791587a-2a7c-4981-a2d8-ab99fffc65b9"
const SignatureiControlProtected string = "{1791587a-2a7c-4981-a2d8-ab99fffc65b9}"

type iControlProtected struct {
	ole.IInspectable
}

type iControlProtectedVtbl struct {
	ole.IInspectableVtbl

	GetDefaultStyleKey uintptr
	SetDefaultStyleKey uintptr
	GetTemplateChild   uintptr
}

func (v *iControlProtected) VTable() *iControlProtectedVtbl {
	return (*iControlProtectedVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControlOverrides string = "a09691df-9824-41fe-b530-b0d8990e64c1"
const SignatureiControlOverrides string = "{a09691df-9824-41fe-b530-b0d8990e64c1}"

type iControlOverrides struct {
	ole.IInspectable
}

type iControlOverridesVtbl struct {
	ole.IInspectableVtbl

	OnPointerEntered              uintptr
	OnPointerPressed              uintptr
	OnPointerMoved                uintptr
	OnPointerReleased             uintptr
	OnPointerExited               uintptr
	OnPointerCaptureLost          uintptr
	OnPointerCanceled             uintptr
	OnPointerWheelChanged         uintptr
	OnTapped                      uintptr
	OnDoubleTapped                uintptr
	OnHolding                     uintptr
	OnRightTapped                 uintptr
	OnManipulationStarting        uintptr
	OnManipulationInertiaStarting uintptr
	OnManipulationStarted         uintptr
	OnManipulationDelta           uintptr
	OnManipulationCompleted       uintptr
	OnKeyUp                       uintptr
	OnKeyDown                     uintptr
	OnGotFocus                    uintptr
	OnLostFocus                   uintptr
	OnDragEnter                   uintptr
	OnDragLeave                   uintptr
	OnDragOver                    uintptr
	OnDrop                        uintptr
}

func (v *iControlOverrides) VTable() *iControlOverridesVtbl {
	return (*iControlOverridesVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiControlOverrides6 string = "e194c96a-d8cc-4339-a0e1-2e9c420879ec"
const SignatureiControlOverrides6 string = "{e194c96a-d8cc-4339-a0e1-2e9c420879ec}"

type iControlOverrides6 struct {
	ole.IInspectable
}

type iControlOverrides6Vtbl struct {
	ole.IInspectableVtbl

	OnPreviewKeyDown    uintptr
	OnPreviewKeyUp      uintptr
	OnCharacterReceived uintptr
}

func (v *iControlOverrides6) VTable() *iControlOverrides6Vtbl {
	return (*iControlOverrides6Vtbl)(unsafe.Pointer(v.RawVTable))
}
