// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureContentControl string = "rc(Windows.UI.Xaml.Controls.ContentControl;{a26dd1dc-cd44-435c-be94-01d6241c231c})"

type ContentControl struct {
	ole.IUnknown
}

func (impl *ContentControl) SetContent(value unsafe.Pointer) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiContentControl))
	defer itf.Release()
	v := (*iContentControl)(unsafe.Pointer(itf))
	return v.SetContent(value)
}

const GUIDiContentControl string = "a26dd1dc-cd44-435c-be94-01d6241c231c"
const SignatureiContentControl string = "{a26dd1dc-cd44-435c-be94-01d6241c231c}"

type iContentControl struct {
	ole.IInspectable
}

type iContentControlVtbl struct {
	ole.IInspectableVtbl

	GetContent                 uintptr
	SetContent                 uintptr
	GetContentTemplate         uintptr
	SetContentTemplate         uintptr
	GetContentTemplateSelector uintptr
	SetContentTemplateSelector uintptr
	GetContentTransitions      uintptr
	SetContentTransitions      uintptr
}

func (v *iContentControl) VTable() *iContentControlVtbl {
	return (*iContentControlVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iContentControl) SetContent(value unsafe.Pointer) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetContent,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in unsafe.Pointer
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiContentControl2 string = "652c208c-8ccf-4399-bd3e-5a015aa1bc03"
const SignatureiContentControl2 string = "{652c208c-8ccf-4399-bd3e-5a015aa1bc03}"

type iContentControl2 struct {
	ole.IInspectable
}

type iContentControl2Vtbl struct {
	ole.IInspectableVtbl

	GetContentTemplateRoot uintptr
}

func (v *iContentControl2) VTable() *iContentControl2Vtbl {
	return (*iContentControl2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiContentControlOverrides string = "5f4c0b10-e38e-4b5d-be1a-5ed04246a635"
const SignatureiContentControlOverrides string = "{5f4c0b10-e38e-4b5d-be1a-5ed04246a635}"

type iContentControlOverrides struct {
	ole.IInspectable
}

type iContentControlOverridesVtbl struct {
	ole.IInspectableVtbl

	OnContentChanged                 uintptr
	OnContentTemplateChanged         uintptr
	OnContentTemplateSelectorChanged uintptr
}

func (v *iContentControlOverrides) VTable() *iContentControlOverridesVtbl {
	return (*iContentControlOverridesVtbl)(unsafe.Pointer(v.RawVTable))
}
