// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
)

const SignatureFlyout string = "rc(Windows.UI.Xaml.Controls.Flyout;{6584ebdf-cbc7-4e19-843a-a14f24a793ea})"

type Flyout struct {
	ole.IUnknown
}

func (impl *Flyout) SetContent(value *xaml.UIElement) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFlyout))
	defer itf.Release()
	v := (*iFlyout)(unsafe.Pointer(itf))
	return v.SetContent(value)
}

const GUIDiFlyout string = "6584ebdf-cbc7-4e19-843a-a14f24a793ea"
const SignatureiFlyout string = "{6584ebdf-cbc7-4e19-843a-a14f24a793ea}"

type iFlyout struct {
	ole.IInspectable
}

type iFlyoutVtbl struct {
	ole.IInspectableVtbl

	GetContent              uintptr
	SetContent              uintptr
	GetFlyoutPresenterStyle uintptr
	SetFlyoutPresenterStyle uintptr
}

func (v *iFlyout) VTable() *iFlyoutVtbl {
	return (*iFlyoutVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iFlyout) SetContent(value *xaml.UIElement) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetContent,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in xaml.UIElement
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
