// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureFontIcon string = "rc(Windows.UI.Xaml.Controls.FontIcon;{d4d61391-39ac-4950-9166-3606c264418b})"

type FontIcon struct {
	ole.IUnknown
}

func (impl *FontIcon) SetGlyph(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFontIcon))
	defer itf.Release()
	v := (*iFontIcon)(unsafe.Pointer(itf))
	return v.SetGlyph(value)
}

func (impl *FontIcon) SetFontSize(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiFontIcon))
	defer itf.Release()
	v := (*iFontIcon)(unsafe.Pointer(itf))
	return v.SetFontSize(value)
}

const GUIDiFontIcon string = "d4d61391-39ac-4950-9166-3606c264418b"
const SignatureiFontIcon string = "{d4d61391-39ac-4950-9166-3606c264418b}"

type iFontIcon struct {
	ole.IInspectable
}

type iFontIconVtbl struct {
	ole.IInspectableVtbl

	GetGlyph      uintptr
	SetGlyph      uintptr
	GetFontSize   uintptr
	SetFontSize   uintptr
	GetFontFamily uintptr
	SetFontFamily uintptr
	GetFontWeight uintptr
	SetFontWeight uintptr
	GetFontStyle  uintptr
	SetFontStyle  uintptr
}

func (v *iFontIcon) VTable() *iFontIconVtbl {
	return (*iFontIconVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iFontIcon) SetGlyph(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetGlyph,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iFontIcon) SetFontSize(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetFontSize,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiFontIcon2 string = "f6ebd84d-37e8-46ee-a574-41ad550482e0"
const SignatureiFontIcon2 string = "{f6ebd84d-37e8-46ee-a574-41ad550482e0}"

type iFontIcon2 struct {
	ole.IInspectable
}

type iFontIcon2Vtbl struct {
	ole.IInspectableVtbl

	GetIsTextScaleFactorEnabled uintptr
	SetIsTextScaleFactorEnabled uintptr
}

func (v *iFontIcon2) VTable() *iFontIcon2Vtbl {
	return (*iFontIcon2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiFontIcon3 string = "6155d919-1c6c-4950-8794-231ef0914d94"
const SignatureiFontIcon3 string = "{6155d919-1c6c-4950-8794-231ef0914d94}"

type iFontIcon3 struct {
	ole.IInspectable
}

type iFontIcon3Vtbl struct {
	ole.IInspectableVtbl

	GetMirroredWhenRightToLeft uintptr
	SetMirroredWhenRightToLeft uintptr
}

func (v *iFontIcon3) VTable() *iFontIcon3Vtbl {
	return (*iFontIcon3Vtbl)(unsafe.Pointer(v.RawVTable))
}
