// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureGrid string = "rc(Windows.UI.Xaml.Controls.Grid;{fd104460-2e15-4ba3-8b8f-fa693a4161e9})"

type Grid struct {
	ole.IUnknown
}

const GUIDiGrid string = "fd104460-2e15-4ba3-8b8f-fa693a4161e9"
const SignatureiGrid string = "{fd104460-2e15-4ba3-8b8f-fa693a4161e9}"

type iGrid struct {
	ole.IInspectable
}

type iGridVtbl struct {
	ole.IInspectableVtbl

	GetRowDefinitions    uintptr
	GetColumnDefinitions uintptr
}

func (v *iGrid) VTable() *iGridVtbl {
	return (*iGridVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiGrid2 string = "f76efa41-380e-45db-be87-9e1326ba4b57"
const SignatureiGrid2 string = "{f76efa41-380e-45db-be87-9e1326ba4b57}"

type iGrid2 struct {
	ole.IInspectable
}

type iGrid2Vtbl struct {
	ole.IInspectableVtbl

	GetBorderBrush     uintptr
	SetBorderBrush     uintptr
	GetBorderThickness uintptr
	SetBorderThickness uintptr
	GetCornerRadius    uintptr
	SetCornerRadius    uintptr
	GetPadding         uintptr
	SetPadding         uintptr
}

func (v *iGrid2) VTable() *iGrid2Vtbl {
	return (*iGrid2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiGrid3 string = "12dfc5fc-2342-4dd2-9e7d-2090a171d1ef"
const SignatureiGrid3 string = "{12dfc5fc-2342-4dd2-9e7d-2090a171d1ef}"

type iGrid3 struct {
	ole.IInspectable
}

type iGrid3Vtbl struct {
	ole.IInspectableVtbl

	GetRowSpacing    uintptr
	SetRowSpacing    uintptr
	GetColumnSpacing uintptr
	SetColumnSpacing uintptr
}

func (v *iGrid3) VTable() *iGrid3Vtbl {
	return (*iGrid3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiGrid4 string = "ed02d274-81f1-5ac2-a0c3-bbdaf5a3ffee"
const SignatureiGrid4 string = "{ed02d274-81f1-5ac2-a0c3-bbdaf5a3ffee}"

type iGrid4 struct {
	ole.IInspectable
}

type iGrid4Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundSizing uintptr
	SetBackgroundSizing uintptr
}

func (v *iGrid4) VTable() *iGrid4Vtbl {
	return (*iGrid4Vtbl)(unsafe.Pointer(v.RawVTable))
}
