// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureIconElement string = "rc(Windows.UI.Xaml.Controls.IconElement;{9af0803b-d04c-467a-bbd5-9b81f02d9a56})"

type IconElement struct {
	ole.IUnknown
}

func (impl *IconElement) SetForeground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiIconElement))
	defer itf.Release()
	v := (*iIconElement)(unsafe.Pointer(itf))
	return v.SetForeground(value)
}

const GUIDiIconElement string = "9af0803b-d04c-467a-bbd5-9b81f02d9a56"
const SignatureiIconElement string = "{9af0803b-d04c-467a-bbd5-9b81f02d9a56}"

type iIconElement struct {
	ole.IInspectable
}

type iIconElementVtbl struct {
	ole.IInspectableVtbl

	GetForeground uintptr
	SetForeground uintptr
}

func (v *iIconElement) VTable() *iIconElementVtbl {
	return (*iIconElementVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iIconElement) SetForeground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetForeground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
