// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/media/playback"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureMediaPlayerElement string = "rc(Windows.UI.Xaml.Controls.MediaPlayerElement;{3b4ca526-2e25-4598-bc71-d491f8e8de39})"

type MediaPlayerElement struct {
	ole.IUnknown
}

func (impl *MediaPlayerElement) SetSource(value *playback.IMediaPlaybackSource) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerElement))
	defer itf.Release()
	v := (*iMediaPlayerElement)(unsafe.Pointer(itf))
	return v.SetSource(value)
}

func (impl *MediaPlayerElement) SetAreTransportControlsEnabled(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerElement))
	defer itf.Release()
	v := (*iMediaPlayerElement)(unsafe.Pointer(itf))
	return v.SetAreTransportControlsEnabled(value)
}

func (impl *MediaPlayerElement) SetStretch(value media.Stretch) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerElement))
	defer itf.Release()
	v := (*iMediaPlayerElement)(unsafe.Pointer(itf))
	return v.SetStretch(value)
}

func (impl *MediaPlayerElement) SetAutoPlay(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerElement))
	defer itf.Release()
	v := (*iMediaPlayerElement)(unsafe.Pointer(itf))
	return v.SetAutoPlay(value)
}

func (impl *MediaPlayerElement) GetMediaPlayer() (*playback.MediaPlayer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerElement))
	defer itf.Release()
	v := (*iMediaPlayerElement)(unsafe.Pointer(itf))
	return v.GetMediaPlayer()
}

const GUIDiMediaPlayerElement string = "3b4ca526-2e25-4598-bc71-d491f8e8de39"
const SignatureiMediaPlayerElement string = "{3b4ca526-2e25-4598-bc71-d491f8e8de39}"

type iMediaPlayerElement struct {
	ole.IInspectable
}

type iMediaPlayerElementVtbl struct {
	ole.IInspectableVtbl

	GetSource                      uintptr
	SetSource                      uintptr
	GetTransportControls           uintptr
	SetTransportControls           uintptr
	GetAreTransportControlsEnabled uintptr
	SetAreTransportControlsEnabled uintptr
	GetPosterSource                uintptr
	SetPosterSource                uintptr
	GetStretch                     uintptr
	SetStretch                     uintptr
	GetAutoPlay                    uintptr
	SetAutoPlay                    uintptr
	GetIsFullWindow                uintptr
	SetIsFullWindow                uintptr
	GetMediaPlayer                 uintptr
	SetMediaPlayer                 uintptr
}

func (v *iMediaPlayerElement) VTable() *iMediaPlayerElementVtbl {
	return (*iMediaPlayerElementVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iMediaPlayerElement) SetSource(value *playback.IMediaPlaybackSource) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSource,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in playback.IMediaPlaybackSource
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iMediaPlayerElement) SetAreTransportControlsEnabled(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetAreTransportControlsEnabled,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iMediaPlayerElement) SetStretch(value media.Stretch) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetStretch,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in media.Stretch
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iMediaPlayerElement) SetAutoPlay(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetAutoPlay,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iMediaPlayerElement) GetMediaPlayer() (*playback.MediaPlayer, error) {
	var out *playback.MediaPlayer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMediaPlayer,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out playback.MediaPlayer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
