// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

type Orientation int32

const SignatureOrientation string = "enum(Windows.UI.Xaml.Controls.Orientation;i4)"

const (
	OrientationVertical   Orientation = 0
	OrientationHorizontal Orientation = 1
)
