// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignaturePanel string = "rc(Windows.UI.Xaml.Controls.Panel;{a50a4bbd-8361-469c-90da-e9a40c7474df})"

type Panel struct {
	ole.IUnknown
}

func (impl *Panel) GetChildren() (*UIElementCollection, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPanel))
	defer itf.Release()
	v := (*iPanel)(unsafe.Pointer(itf))
	return v.GetChildren()
}

func (impl *Panel) SetBackground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPanel))
	defer itf.Release()
	v := (*iPanel)(unsafe.Pointer(itf))
	return v.SetBackground(value)
}

const GUIDiPanel string = "a50a4bbd-8361-469c-90da-e9a40c7474df"
const SignatureiPanel string = "{a50a4bbd-8361-469c-90da-e9a40c7474df}"

type iPanel struct {
	ole.IInspectable
}

type iPanelVtbl struct {
	ole.IInspectableVtbl

	GetChildren            uintptr
	GetBackground          uintptr
	SetBackground          uintptr
	GetIsItemsHost         uintptr
	GetChildrenTransitions uintptr
	SetChildrenTransitions uintptr
}

func (v *iPanel) VTable() *iPanelVtbl {
	return (*iPanelVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPanel) GetChildren() (*UIElementCollection, error) {
	var out *UIElementCollection
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetChildren,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out UIElementCollection
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iPanel) SetBackground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetBackground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiPanel2 string = "709133c7-38f3-5083-a4bb-06a548a1d231"
const SignatureiPanel2 string = "{709133c7-38f3-5083-a4bb-06a548a1d231}"

type iPanel2 struct {
	ole.IInspectable
}

type iPanel2Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundTransition uintptr
	SetBackgroundTransition uintptr
}

func (v *iPanel2) VTable() *iPanel2Vtbl {
	return (*iPanel2Vtbl)(unsafe.Pointer(v.RawVTable))
}
