// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignaturePasswordBox string = "rc(Windows.UI.Xaml.Controls.PasswordBox;{02b9aa11-0b47-4e7d-ad91-3a4168ed230d})"

type PasswordBox struct {
	ole.IUnknown
}

func NewPasswordBox() (*PasswordBox, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Controls.PasswordBox")
	if err != nil {
		return nil, err
	}
	return (*PasswordBox)(unsafe.Pointer(inspectable)), nil
}

func (impl *PasswordBox) GetPassword() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordBox))
	defer itf.Release()
	v := (*iPasswordBox)(unsafe.Pointer(itf))
	return v.GetPassword()
}

func (impl *PasswordBox) SetPassword(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordBox))
	defer itf.Release()
	v := (*iPasswordBox)(unsafe.Pointer(itf))
	return v.SetPassword(value)
}

func (impl *PasswordBox) SetPlaceholderText(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiPasswordBox2))
	defer itf.Release()
	v := (*iPasswordBox2)(unsafe.Pointer(itf))
	return v.SetPlaceholderText(value)
}

const GUIDiPasswordBox string = "02b9aa11-0b47-4e7d-ad91-3a4168ed230d"
const SignatureiPasswordBox string = "{02b9aa11-0b47-4e7d-ad91-3a4168ed230d}"

type iPasswordBox struct {
	ole.IInspectable
}

type iPasswordBoxVtbl struct {
	ole.IInspectableVtbl

	GetPassword                      uintptr
	SetPassword                      uintptr
	GetPasswordChar                  uintptr
	SetPasswordChar                  uintptr
	GetIsPasswordRevealButtonEnabled uintptr
	SetIsPasswordRevealButtonEnabled uintptr
	GetMaxLength                     uintptr
	SetMaxLength                     uintptr
	AddPasswordChanged               uintptr
	RemovePasswordChanged            uintptr
	AddContextMenuOpening            uintptr
	RemoveContextMenuOpening         uintptr
	SelectAll                        uintptr
}

func (v *iPasswordBox) VTable() *iPasswordBoxVtbl {
	return (*iPasswordBoxVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPasswordBox) GetPassword() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPassword,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iPasswordBox) SetPassword(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPassword,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiPasswordBox2 string = "5ed738df-212f-4aeb-b5b8-2c219aec3c0c"
const SignatureiPasswordBox2 string = "{5ed738df-212f-4aeb-b5b8-2c219aec3c0c}"

type iPasswordBox2 struct {
	ole.IInspectable
}

type iPasswordBox2Vtbl struct {
	ole.IInspectableVtbl

	GetHeader                                    uintptr
	SetHeader                                    uintptr
	GetHeaderTemplate                            uintptr
	SetHeaderTemplate                            uintptr
	GetPlaceholderText                           uintptr
	SetPlaceholderText                           uintptr
	GetSelectionHighlightColor                   uintptr
	SetSelectionHighlightColor                   uintptr
	GetPreventKeyboardDisplayOnProgrammaticFocus uintptr
	SetPreventKeyboardDisplayOnProgrammaticFocus uintptr
	AddPaste                                     uintptr
	RemovePaste                                  uintptr
}

func (v *iPasswordBox2) VTable() *iPasswordBox2Vtbl {
	return (*iPasswordBox2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iPasswordBox2) SetPlaceholderText(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPlaceholderText,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiPasswordBox3 string = "6024d9d1-56b7-41f0-9558-3934c14244d6"
const SignatureiPasswordBox3 string = "{6024d9d1-56b7-41f0-9558-3934c14244d6}"

type iPasswordBox3 struct {
	ole.IInspectable
}

type iPasswordBox3Vtbl struct {
	ole.IInspectableVtbl

	GetPasswordRevealMode uintptr
	SetPasswordRevealMode uintptr
	GetTextReadingOrder   uintptr
	SetTextReadingOrder   uintptr
	GetInputScope         uintptr
	SetInputScope         uintptr
}

func (v *iPasswordBox3) VTable() *iPasswordBox3Vtbl {
	return (*iPasswordBox3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiPasswordBox4 string = "569f4343-8e6c-44bf-808d-0e03964ed32f"
const SignatureiPasswordBox4 string = "{569f4343-8e6c-44bf-808d-0e03964ed32f}"

type iPasswordBox4 struct {
	ole.IInspectable
}

type iPasswordBox4Vtbl struct {
	ole.IInspectableVtbl

	AddPasswordChanging    uintptr
	RemovePasswordChanging uintptr
}

func (v *iPasswordBox4) VTable() *iPasswordBox4Vtbl {
	return (*iPasswordBox4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiPasswordBox5 string = "f96c2753-e1d4-5142-86c2-7318bfbbc705"
const SignatureiPasswordBox5 string = "{f96c2753-e1d4-5142-86c2-7318bfbbc705}"

type iPasswordBox5 struct {
	ole.IInspectable
}

type iPasswordBox5Vtbl struct {
	ole.IInspectableVtbl

	GetCanPasteClipboardContent uintptr
	GetSelectionFlyout          uintptr
	SetSelectionFlyout          uintptr
	GetDescription              uintptr
	SetDescription              uintptr
	PasteFromClipboard          uintptr
}

func (v *iPasswordBox5) VTable() *iPasswordBox5Vtbl {
	return (*iPasswordBox5Vtbl)(unsafe.Pointer(v.RawVTable))
}
