// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureScrollViewer string = "rc(Windows.UI.Xaml.Controls.ScrollViewer;{64e9be00-4dc1-493d-abe7-cbd3c577490d})"

type ScrollViewer struct {
	ole.IUnknown
}

func NewScrollViewer() (*ScrollViewer, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Controls.ScrollViewer")
	if err != nil {
		return nil, err
	}
	return (*ScrollViewer)(unsafe.Pointer(inspectable)), nil
}

func (impl *ScrollViewer) SetHorizontalScrollBarVisibility(value ScrollBarVisibility) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiScrollViewer))
	defer itf.Release()
	v := (*iScrollViewer)(unsafe.Pointer(itf))
	return v.SetHorizontalScrollBarVisibility(value)
}

func (impl *ScrollViewer) SetVerticalScrollBarVisibility(value ScrollBarVisibility) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiScrollViewer))
	defer itf.Release()
	v := (*iScrollViewer)(unsafe.Pointer(itf))
	return v.SetVerticalScrollBarVisibility(value)
}

func (impl *ScrollViewer) SetHorizontalScrollMode(value ScrollMode) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiScrollViewer))
	defer itf.Release()
	v := (*iScrollViewer)(unsafe.Pointer(itf))
	return v.SetHorizontalScrollMode(value)
}

func (impl *ScrollViewer) SetVerticalScrollMode(value ScrollMode) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiScrollViewer))
	defer itf.Release()
	v := (*iScrollViewer)(unsafe.Pointer(itf))
	return v.SetVerticalScrollMode(value)
}

const GUIDiScrollViewer string = "64e9be00-4dc1-493d-abe7-cbd3c577490d"
const SignatureiScrollViewer string = "{64e9be00-4dc1-493d-abe7-cbd3c577490d}"

type iScrollViewer struct {
	ole.IInspectable
}

type iScrollViewerVtbl struct {
	ole.IInspectableVtbl

	GetHorizontalScrollBarVisibility         uintptr
	SetHorizontalScrollBarVisibility         uintptr
	GetVerticalScrollBarVisibility           uintptr
	SetVerticalScrollBarVisibility           uintptr
	GetIsHorizontalRailEnabled               uintptr
	SetIsHorizontalRailEnabled               uintptr
	GetIsVerticalRailEnabled                 uintptr
	SetIsVerticalRailEnabled                 uintptr
	GetIsHorizontalScrollChainingEnabled     uintptr
	SetIsHorizontalScrollChainingEnabled     uintptr
	GetIsVerticalScrollChainingEnabled       uintptr
	SetIsVerticalScrollChainingEnabled       uintptr
	GetIsZoomChainingEnabled                 uintptr
	SetIsZoomChainingEnabled                 uintptr
	GetIsScrollInertiaEnabled                uintptr
	SetIsScrollInertiaEnabled                uintptr
	GetIsZoomInertiaEnabled                  uintptr
	SetIsZoomInertiaEnabled                  uintptr
	GetHorizontalScrollMode                  uintptr
	SetHorizontalScrollMode                  uintptr
	GetVerticalScrollMode                    uintptr
	SetVerticalScrollMode                    uintptr
	GetZoomMode                              uintptr
	SetZoomMode                              uintptr
	GetHorizontalSnapPointsAlignment         uintptr
	SetHorizontalSnapPointsAlignment         uintptr
	GetVerticalSnapPointsAlignment           uintptr
	SetVerticalSnapPointsAlignment           uintptr
	GetHorizontalSnapPointsType              uintptr
	SetHorizontalSnapPointsType              uintptr
	GetVerticalSnapPointsType                uintptr
	SetVerticalSnapPointsType                uintptr
	GetZoomSnapPointsType                    uintptr
	SetZoomSnapPointsType                    uintptr
	GetHorizontalOffset                      uintptr
	GetViewportWidth                         uintptr
	GetScrollableWidth                       uintptr
	GetComputedHorizontalScrollBarVisibility uintptr
	GetExtentWidth                           uintptr
	GetVerticalOffset                        uintptr
	GetViewportHeight                        uintptr
	GetScrollableHeight                      uintptr
	GetComputedVerticalScrollBarVisibility   uintptr
	GetExtentHeight                          uintptr
	GetMinZoomFactor                         uintptr
	SetMinZoomFactor                         uintptr
	GetMaxZoomFactor                         uintptr
	SetMaxZoomFactor                         uintptr
	GetZoomFactor                            uintptr
	GetZoomSnapPoints                        uintptr
	AddViewChanged                           uintptr
	RemoveViewChanged                        uintptr
	ScrollToHorizontalOffset                 uintptr
	ScrollToVerticalOffset                   uintptr
	ZoomToFactor                             uintptr
	InvalidateScrollInfo                     uintptr
	GetIsDeferredScrollingEnabled            uintptr
	SetIsDeferredScrollingEnabled            uintptr
	GetBringIntoViewOnFocusChange            uintptr
	SetBringIntoViewOnFocusChange            uintptr
}

func (v *iScrollViewer) VTable() *iScrollViewerVtbl {
	return (*iScrollViewerVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iScrollViewer) SetHorizontalScrollBarVisibility(value ScrollBarVisibility) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHorizontalScrollBarVisibility,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ScrollBarVisibility
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iScrollViewer) SetVerticalScrollBarVisibility(value ScrollBarVisibility) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetVerticalScrollBarVisibility,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ScrollBarVisibility
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iScrollViewer) SetHorizontalScrollMode(value ScrollMode) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHorizontalScrollMode,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ScrollMode
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iScrollViewer) SetVerticalScrollMode(value ScrollMode) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetVerticalScrollMode,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ScrollMode
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiScrollViewer2 string = "64e9be10-4dd1-494d-abf7-cbd3c577491d"
const SignatureiScrollViewer2 string = "{64e9be10-4dd1-494d-abf7-cbd3c577491d}"

type iScrollViewer2 struct {
	ole.IInspectable
}

type iScrollViewer2Vtbl struct {
	ole.IInspectableVtbl

	GetTopLeftHeader                uintptr
	SetTopLeftHeader                uintptr
	GetLeftHeader                   uintptr
	SetLeftHeader                   uintptr
	GetTopHeader                    uintptr
	SetTopHeader                    uintptr
	AddViewChanging                 uintptr
	RemoveViewChanging              uintptr
	ChangeView                      uintptr
	ChangeViewWithOptionalAnimation uintptr
}

func (v *iScrollViewer2) VTable() *iScrollViewer2Vtbl {
	return (*iScrollViewer2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiScrollViewer3 string = "74e9be21-5de2-595e-bc08-dbd3c577492c"
const SignatureiScrollViewer3 string = "{74e9be21-5de2-595e-bc08-dbd3c577492c}"

type iScrollViewer3 struct {
	ole.IInspectable
}

type iScrollViewer3Vtbl struct {
	ole.IInspectableVtbl

	AddDirectManipulationStarted      uintptr
	RemoveDirectManipulationStarted   uintptr
	AddDirectManipulationCompleted    uintptr
	RemoveDirectManipulationCompleted uintptr
}

func (v *iScrollViewer3) VTable() *iScrollViewer3Vtbl {
	return (*iScrollViewer3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiScrollViewer4 string = "786fb0c4-50a9-5a45-8a92-7bf372e19098"
const SignatureiScrollViewer4 string = "{786fb0c4-50a9-5a45-8a92-7bf372e19098}"

type iScrollViewer4 struct {
	ole.IInspectable
}

type iScrollViewer4Vtbl struct {
	ole.IInspectableVtbl

	GetReduceViewportForCoreInputViewOcclusions uintptr
	SetReduceViewportForCoreInputViewOcclusions uintptr
	GetHorizontalAnchorRatio                    uintptr
	SetHorizontalAnchorRatio                    uintptr
	GetVerticalAnchorRatio                      uintptr
	SetVerticalAnchorRatio                      uintptr
	GetCanContentRenderOutsideBounds            uintptr
	SetCanContentRenderOutsideBounds            uintptr
	AddAnchorRequested                          uintptr
	RemoveAnchorRequested                       uintptr
}

func (v *iScrollViewer4) VTable() *iScrollViewer4Vtbl {
	return (*iScrollViewer4Vtbl)(unsafe.Pointer(v.RawVTable))
}
