// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

type ScrollMode int32

const SignatureScrollMode string = "enum(Windows.UI.Xaml.Controls.ScrollMode;i4)"

const (
	ScrollModeDisabled ScrollMode = 0
	ScrollModeEnabled  ScrollMode = 1
	ScrollModeAuto     ScrollMode = 2
)
