// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

type ScrollBarVisibility int32

const SignatureScrollBarVisibility string = "enum(Windows.UI.Xaml.Controls.ScrollBarVisibility;i4)"

const (
	ScrollBarVisibilityDisabled ScrollBarVisibility = 0
	ScrollBarVisibilityAuto     ScrollBarVisibility = 1
	ScrollBarVisibilityHidden   ScrollBarVisibility = 2
	ScrollBarVisibilityVisible  ScrollBarVisibility = 3
)
