// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStackPanel string = "rc(Windows.UI.Xaml.Controls.StackPanel;{b8ae8fe2-d641-4fd7-80b4-7439207d2798})"

type StackPanel struct {
	ole.IUnknown
}

func (impl *StackPanel) SetOrientation(value Orientation) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStackPanel))
	defer itf.Release()
	v := (*iStackPanel)(unsafe.Pointer(itf))
	return v.SetOrientation(value)
}

func (impl *StackPanel) SetSpacing(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStackPanel4))
	defer itf.Release()
	v := (*iStackPanel4)(unsafe.Pointer(itf))
	return v.SetSpacing(value)
}

const GUIDiStackPanel string = "b8ae8fe2-d641-4fd7-80b4-7439207d2798"
const SignatureiStackPanel string = "{b8ae8fe2-d641-4fd7-80b4-7439207d2798}"

type iStackPanel struct {
	ole.IInspectable
}

type iStackPanelVtbl struct {
	ole.IInspectableVtbl

	GetAreScrollSnapPointsRegular uintptr
	SetAreScrollSnapPointsRegular uintptr
	GetOrientation                uintptr
	SetOrientation                uintptr
}

func (v *iStackPanel) VTable() *iStackPanelVtbl {
	return (*iStackPanelVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStackPanel) SetOrientation(value Orientation) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOrientation,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in Orientation
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStackPanel2 string = "36f23359-040e-48f7-9a98-f2664591959c"
const SignatureiStackPanel2 string = "{36f23359-040e-48f7-9a98-f2664591959c}"

type iStackPanel2 struct {
	ole.IInspectable
}

type iStackPanel2Vtbl struct {
	ole.IInspectableVtbl

	GetBorderBrush     uintptr
	SetBorderBrush     uintptr
	GetBorderThickness uintptr
	SetBorderThickness uintptr
	GetCornerRadius    uintptr
	SetCornerRadius    uintptr
	GetPadding         uintptr
	SetPadding         uintptr
}

func (v *iStackPanel2) VTable() *iStackPanel2Vtbl {
	return (*iStackPanel2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiStackPanel4 string = "43ebf7f6-3196-412e-8a95-add002ff43f0"
const SignatureiStackPanel4 string = "{43ebf7f6-3196-412e-8a95-add002ff43f0}"

type iStackPanel4 struct {
	ole.IInspectable
}

type iStackPanel4Vtbl struct {
	ole.IInspectableVtbl

	GetSpacing uintptr
	SetSpacing uintptr
}

func (v *iStackPanel4) VTable() *iStackPanel4Vtbl {
	return (*iStackPanel4Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStackPanel4) SetSpacing(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSpacing,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStackPanel5 string = "f73e3117-61a8-5a01-865e-88511c04a992"
const SignatureiStackPanel5 string = "{f73e3117-61a8-5a01-865e-88511c04a992}"

type iStackPanel5 struct {
	ole.IInspectable
}

type iStackPanel5Vtbl struct {
	ole.IInspectableVtbl

	GetBackgroundSizing uintptr
	SetBackgroundSizing uintptr
}

func (v *iStackPanel5) VTable() *iStackPanel5Vtbl {
	return (*iStackPanel5Vtbl)(unsafe.Pointer(v.RawVTable))
}
