// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml/media"
)

const SignatureTextBlock string = "rc(Windows.UI.Xaml.Controls.TextBlock;{ae2d9271-3b4a-45fc-8468-f7949548f4d5})"

type TextBlock struct {
	ole.IUnknown
}

func NewTextBlock() (*TextBlock, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Controls.TextBlock")
	if err != nil {
		return nil, err
	}
	return (*TextBlock)(unsafe.Pointer(inspectable)), nil
}

func (impl *TextBlock) SetFontSize(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBlock))
	defer itf.Release()
	v := (*iTextBlock)(unsafe.Pointer(itf))
	return v.SetFontSize(value)
}

func (impl *TextBlock) SetForeground(value *media.Brush) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBlock))
	defer itf.Release()
	v := (*iTextBlock)(unsafe.Pointer(itf))
	return v.SetForeground(value)
}

func (impl *TextBlock) SetText(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBlock))
	defer itf.Release()
	v := (*iTextBlock)(unsafe.Pointer(itf))
	return v.SetText(value)
}

const GUIDiTextBlock string = "ae2d9271-3b4a-45fc-8468-f7949548f4d5"
const SignatureiTextBlock string = "{ae2d9271-3b4a-45fc-8468-f7949548f4d5}"

type iTextBlock struct {
	ole.IInspectable
}

type iTextBlockVtbl struct {
	ole.IInspectableVtbl

	GetFontSize               uintptr
	SetFontSize               uintptr
	GetFontFamily             uintptr
	SetFontFamily             uintptr
	GetFontWeight             uintptr
	SetFontWeight             uintptr
	GetFontStyle              uintptr
	SetFontStyle              uintptr
	GetFontStretch            uintptr
	SetFontStretch            uintptr
	GetCharacterSpacing       uintptr
	SetCharacterSpacing       uintptr
	GetForeground             uintptr
	SetForeground             uintptr
	GetTextWrapping           uintptr
	SetTextWrapping           uintptr
	GetTextTrimming           uintptr
	SetTextTrimming           uintptr
	GetTextAlignment          uintptr
	SetTextAlignment          uintptr
	GetText                   uintptr
	SetText                   uintptr
	GetInlines                uintptr
	GetPadding                uintptr
	SetPadding                uintptr
	GetLineHeight             uintptr
	SetLineHeight             uintptr
	GetLineStackingStrategy   uintptr
	SetLineStackingStrategy   uintptr
	GetIsTextSelectionEnabled uintptr
	SetIsTextSelectionEnabled uintptr
	GetSelectedText           uintptr
	GetContentStart           uintptr
	GetContentEnd             uintptr
	GetSelectionStart         uintptr
	GetSelectionEnd           uintptr
	GetBaselineOffset         uintptr
	AddSelectionChanged       uintptr
	RemoveSelectionChanged    uintptr
	AddContextMenuOpening     uintptr
	RemoveContextMenuOpening  uintptr
	SelectAll                 uintptr
	Select                    uintptr
	Focus                     uintptr
}

func (v *iTextBlock) VTable() *iTextBlockVtbl {
	return (*iTextBlockVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iTextBlock) SetFontSize(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetFontSize,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iTextBlock) SetForeground(value *media.Brush) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetForeground,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in media.Brush
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iTextBlock) SetText(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetText,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiTextBlock2 string = "45206a4c-0a4e-4fbf-aee9-335d5a205f6e"
const SignatureiTextBlock2 string = "{45206a4c-0a4e-4fbf-aee9-335d5a205f6e}"

type iTextBlock2 struct {
	ole.IInspectable
}

type iTextBlock2Vtbl struct {
	ole.IInspectableVtbl

	GetSelectionHighlightColor uintptr
	SetSelectionHighlightColor uintptr
	GetMaxLines                uintptr
	SetMaxLines                uintptr
	GetTextLineBounds          uintptr
	SetTextLineBounds          uintptr
	GetOpticalMarginAlignment  uintptr
	SetOpticalMarginAlignment  uintptr
	GetIsColorFontEnabled      uintptr
	SetIsColorFontEnabled      uintptr
	GetTextReadingOrder        uintptr
	SetTextReadingOrder        uintptr
}

func (v *iTextBlock2) VTable() *iTextBlock2Vtbl {
	return (*iTextBlock2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBlock3 string = "b651dd5a-424b-48c3-9b67-486f4e139899"
const SignatureiTextBlock3 string = "{b651dd5a-424b-48c3-9b67-486f4e139899}"

type iTextBlock3 struct {
	ole.IInspectable
}

type iTextBlock3Vtbl struct {
	ole.IInspectableVtbl

	GetIsTextScaleFactorEnabled uintptr
	SetIsTextScaleFactorEnabled uintptr
}

func (v *iTextBlock3) VTable() *iTextBlock3Vtbl {
	return (*iTextBlock3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBlock4 string = "b014f270-9808-4adc-b452-60cda54100c1"
const SignatureiTextBlock4 string = "{b014f270-9808-4adc-b452-60cda54100c1}"

type iTextBlock4 struct {
	ole.IInspectable
}

type iTextBlock4Vtbl struct {
	ole.IInspectableVtbl

	GetAlphaMask uintptr
}

func (v *iTextBlock4) VTable() *iTextBlock4Vtbl {
	return (*iTextBlock4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBlock5 string = "624a2d38-edbd-4a5a-b678-e49f1e07afbd"
const SignatureiTextBlock5 string = "{624a2d38-edbd-4a5a-b678-e49f1e07afbd}"

type iTextBlock5 struct {
	ole.IInspectable
}

type iTextBlock5Vtbl struct {
	ole.IInspectableVtbl

	GetTextDecorations uintptr
	SetTextDecorations uintptr
}

func (v *iTextBlock5) VTable() *iTextBlock5Vtbl {
	return (*iTextBlock5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBlock6 string = "31816cd9-0404-410f-91ec-33b0a0bb92b2"
const SignatureiTextBlock6 string = "{31816cd9-0404-410f-91ec-33b0a0bb92b2}"

type iTextBlock6 struct {
	ole.IInspectable
}

type iTextBlock6Vtbl struct {
	ole.IInspectableVtbl

	GetIsTextTrimmed           uintptr
	GetHorizontalTextAlignment uintptr
	SetHorizontalTextAlignment uintptr
	GetTextHighlighters        uintptr
	AddIsTextTrimmedChanged    uintptr
	RemoveIsTextTrimmedChanged uintptr
}

func (v *iTextBlock6) VTable() *iTextBlock6Vtbl {
	return (*iTextBlock6Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBlock7 string = "dfe20a4e-8be7-5e33-9f37-72416875b121"
const SignatureiTextBlock7 string = "{dfe20a4e-8be7-5e33-9f37-72416875b121}"

type iTextBlock7 struct {
	ole.IInspectable
}

type iTextBlock7Vtbl struct {
	ole.IInspectableVtbl

	GetSelectionFlyout       uintptr
	SetSelectionFlyout       uintptr
	CopySelectionToClipboard uintptr
}

func (v *iTextBlock7) VTable() *iTextBlock7Vtbl {
	return (*iTextBlock7Vtbl)(unsafe.Pointer(v.RawVTable))
}
