// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureTextBox string = "rc(Windows.UI.Xaml.Controls.TextBox;{e48f5a8b-1dff-4352-a1f4-e516514ec882})"

type TextBox struct {
	ole.IUnknown
}

func (impl *TextBox) GetText() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBox))
	defer itf.Release()
	v := (*iTextBox)(unsafe.Pointer(itf))
	return v.GetText()
}

func (impl *TextBox) SetText(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBox))
	defer itf.Release()
	v := (*iTextBox)(unsafe.Pointer(itf))
	return v.SetText(value)
}

func (impl *TextBox) SetPlaceholderText(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiTextBox2))
	defer itf.Release()
	v := (*iTextBox2)(unsafe.Pointer(itf))
	return v.SetPlaceholderText(value)
}

const GUIDiTextBox string = "e48f5a8b-1dff-4352-a1f4-e516514ec882"
const SignatureiTextBox string = "{e48f5a8b-1dff-4352-a1f4-e516514ec882}"

type iTextBox struct {
	ole.IInspectable
}

type iTextBoxVtbl struct {
	ole.IInspectableVtbl

	GetText                    uintptr
	SetText                    uintptr
	GetSelectedText            uintptr
	SetSelectedText            uintptr
	GetSelectionLength         uintptr
	SetSelectionLength         uintptr
	GetSelectionStart          uintptr
	SetSelectionStart          uintptr
	GetMaxLength               uintptr
	SetMaxLength               uintptr
	GetIsReadOnly              uintptr
	SetIsReadOnly              uintptr
	GetAcceptsReturn           uintptr
	SetAcceptsReturn           uintptr
	GetTextAlignment           uintptr
	SetTextAlignment           uintptr
	GetTextWrapping            uintptr
	SetTextWrapping            uintptr
	GetIsSpellCheckEnabled     uintptr
	SetIsSpellCheckEnabled     uintptr
	GetIsTextPredictionEnabled uintptr
	SetIsTextPredictionEnabled uintptr
	GetInputScope              uintptr
	SetInputScope              uintptr
	AddTextChanged             uintptr
	RemoveTextChanged          uintptr
	AddSelectionChanged        uintptr
	RemoveSelectionChanged     uintptr
	AddContextMenuOpening      uintptr
	RemoveContextMenuOpening   uintptr
	Select                     uintptr
	SelectAll                  uintptr
	GetRectFromCharacterIndex  uintptr
}

func (v *iTextBox) VTable() *iTextBoxVtbl {
	return (*iTextBoxVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iTextBox) GetText() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetText,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iTextBox) SetText(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetText,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiTextBox2 string = "f7168c00-1432-462a-9405-38f385bfc37c"
const SignatureiTextBox2 string = "{f7168c00-1432-462a-9405-38f385bfc37c}"

type iTextBox2 struct {
	ole.IInspectable
}

type iTextBox2Vtbl struct {
	ole.IInspectableVtbl

	GetHeader                                    uintptr
	SetHeader                                    uintptr
	GetHeaderTemplate                            uintptr
	SetHeaderTemplate                            uintptr
	GetPlaceholderText                           uintptr
	SetPlaceholderText                           uintptr
	GetSelectionHighlightColor                   uintptr
	SetSelectionHighlightColor                   uintptr
	GetPreventKeyboardDisplayOnProgrammaticFocus uintptr
	SetPreventKeyboardDisplayOnProgrammaticFocus uintptr
	GetIsColorFontEnabled                        uintptr
	SetIsColorFontEnabled                        uintptr
	AddPaste                                     uintptr
	RemovePaste                                  uintptr
}

func (v *iTextBox2) VTable() *iTextBox2Vtbl {
	return (*iTextBox2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iTextBox2) SetPlaceholderText(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPlaceholderText,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiTextBox3 string = "7df18c3c-2826-425e-9a94-00b7f73f3756"
const SignatureiTextBox3 string = "{7df18c3c-2826-425e-9a94-00b7f73f3756}"

type iTextBox3 struct {
	ole.IInspectable
}

type iTextBox3Vtbl struct {
	ole.IInspectableVtbl

	AddTextCompositionStarted          uintptr
	RemoveTextCompositionStarted       uintptr
	AddTextCompositionChanged          uintptr
	RemoveTextCompositionChanged       uintptr
	AddTextCompositionEnded            uintptr
	RemoveTextCompositionEnded         uintptr
	GetTextReadingOrder                uintptr
	SetTextReadingOrder                uintptr
	GetDesiredCandidateWindowAlignment uintptr
	SetDesiredCandidateWindowAlignment uintptr
	AddCandidateWindowBoundsChanged    uintptr
	RemoveCandidateWindowBoundsChanged uintptr
	AddTextChanging                    uintptr
	RemoveTextChanging                 uintptr
}

func (v *iTextBox3) VTable() *iTextBox3Vtbl {
	return (*iTextBox3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBox4 string = "b5f1a675-cce1-45af-aef9-c4787bbb5e30"
const SignatureiTextBox4 string = "{b5f1a675-cce1-45af-aef9-c4787bbb5e30}"

type iTextBox4 struct {
	ole.IInspectable
}

type iTextBox4Vtbl struct {
	ole.IInspectableVtbl

	GetLinguisticAlternativesAsync uintptr
}

func (v *iTextBox4) VTable() *iTextBox4Vtbl {
	return (*iTextBox4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBox5 string = "35f9cfc1-4176-44f4-b756-e9ccc4399805"
const SignatureiTextBox5 string = "{35f9cfc1-4176-44f4-b756-e9ccc4399805}"

type iTextBox5 struct {
	ole.IInspectable
}

type iTextBox5Vtbl struct {
	ole.IInspectableVtbl

	GetSelectionHighlightColorWhenNotFocused uintptr
	SetSelectionHighlightColorWhenNotFocused uintptr
}

func (v *iTextBox5) VTable() *iTextBox5Vtbl {
	return (*iTextBox5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBox6 string = "41ff2d07-5085-4e52-a51c-f94b06cd558b"
const SignatureiTextBox6 string = "{41ff2d07-5085-4e52-a51c-f94b06cd558b}"

type iTextBox6 struct {
	ole.IInspectable
}

type iTextBox6Vtbl struct {
	ole.IInspectableVtbl

	GetHorizontalTextAlignment uintptr
	SetHorizontalTextAlignment uintptr
	GetCharacterCasing         uintptr
	SetCharacterCasing         uintptr
	GetPlaceholderForeground   uintptr
	SetPlaceholderForeground   uintptr
	AddCopyingToClipboard      uintptr
	RemoveCopyingToClipboard   uintptr
	AddCuttingToClipboard      uintptr
	RemoveCuttingToClipboard   uintptr
	AddBeforeTextChanging      uintptr
	RemoveBeforeTextChanging   uintptr
}

func (v *iTextBox6) VTable() *iTextBox6Vtbl {
	return (*iTextBox6Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBox7 string = "da4911f9-ffe1-4c6a-ac6d-1b4a174ccf80"
const SignatureiTextBox7 string = "{da4911f9-ffe1-4c6a-ac6d-1b4a174ccf80}"

type iTextBox7 struct {
	ole.IInspectable
}

type iTextBox7Vtbl struct {
	ole.IInspectableVtbl

	GetHandwritingView          uintptr
	SetHandwritingView          uintptr
	GetIsHandwritingViewEnabled uintptr
	SetIsHandwritingViewEnabled uintptr
}

func (v *iTextBox7) VTable() *iTextBox7Vtbl {
	return (*iTextBox7Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiTextBox8 string = "1eb6d027-0317-5c37-8aea-f747ae7f0463"
const SignatureiTextBox8 string = "{1eb6d027-0317-5c37-8aea-f747ae7f0463}"

type iTextBox8 struct {
	ole.IInspectable
}

type iTextBox8Vtbl struct {
	ole.IInspectableVtbl

	GetCanPasteClipboardContent uintptr
	GetCanUndo                  uintptr
	GetCanRedo                  uintptr
	GetSelectionFlyout          uintptr
	SetSelectionFlyout          uintptr
	GetProofingMenuFlyout       uintptr
	GetDescription              uintptr
	SetDescription              uintptr
	AddSelectionChanging        uintptr
	RemoveSelectionChanging     uintptr
	Undo                        uintptr
	Redo                        uintptr
	PasteFromClipboard          uintptr
	CopySelectionToClipboard    uintptr
	CutSelectionToClipboard     uintptr
	ClearUndoRedoHistory        uintptr
}

func (v *iTextBox8) VTable() *iTextBox8Vtbl {
	return (*iTextBox8Vtbl)(unsafe.Pointer(v.RawVTable))
}
