// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/ui/xaml"
)

const SignatureToolTipService string = "rc(Windows.UI.Xaml.Controls.ToolTipService;{03a55f87-bfcc-4a1e-8fea-98f610832cea})"

type ToolTipService struct {
	ole.IUnknown
}

const GUIDiToolTipService string = "03a55f87-bfcc-4a1e-8fea-98f610832cea"
const SignatureiToolTipService string = "{03a55f87-bfcc-4a1e-8fea-98f610832cea}"

type iToolTipService struct {
	ole.IInspectable
}

type iToolTipServiceVtbl struct {
	ole.IInspectableVtbl
}

func (v *iToolTipService) VTable() *iToolTipServiceVtbl {
	return (*iToolTipServiceVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiToolTipServiceStatics string = "86e649f8-e245-48aa-a8c8-d1073ed76319"
const SignatureiToolTipServiceStatics string = "{86e649f8-e245-48aa-a8c8-d1073ed76319}"

type iToolTipServiceStatics struct {
	ole.IInspectable
}

type iToolTipServiceStaticsVtbl struct {
	ole.IInspectableVtbl

	ToolTipServiceGetPlacementProperty       uintptr
	ToolTipServiceGetPlacement               uintptr
	ToolTipServiceSetPlacement               uintptr
	ToolTipServiceGetPlacementTargetProperty uintptr
	ToolTipServiceGetPlacementTarget         uintptr
	ToolTipServiceSetPlacementTarget         uintptr
	ToolTipServiceGetToolTipProperty         uintptr
	ToolTipServiceGetToolTip                 uintptr
	ToolTipServiceSetToolTip                 uintptr
}

func (v *iToolTipServiceStatics) VTable() *iToolTipServiceStaticsVtbl {
	return (*iToolTipServiceStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func ToolTipServiceSetToolTip(element *xaml.DependencyObject, value unsafe.Pointer) error {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Xaml.Controls.ToolTipService", ole.NewGUID(GUIDiToolTipServiceStatics))
	if err != nil {
		return err
	}
	v := (*iToolTipServiceStatics)(unsafe.Pointer(inspectable))

	hr, _, _ := syscall.SyscallN(
		v.VTable().ToolTipServiceSetToolTip,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(element)), // in xaml.DependencyObject
		uintptr(value),                   // in unsafe.Pointer
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
