// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureUIElementCollection string = "rc(Windows.UI.Xaml.Controls.UIElementCollection;{d6602d54-88f6-43f6-85d8-a9d914a6dd3b})"

type UIElementCollection struct {
	ole.IUnknown
}

const GUIDiUIElementCollection string = "d6602d54-88f6-43f6-85d8-a9d914a6dd3b"
const SignatureiUIElementCollection string = "{d6602d54-88f6-43f6-85d8-a9d914a6dd3b}"

type iUIElementCollection struct {
	ole.IInspectable
}

type iUIElementCollectionVtbl struct {
	ole.IInspectableVtbl

	Move uintptr
}

func (v *iUIElementCollection) VTable() *iUIElementCollectionVtbl {
	return (*iUIElementCollectionVtbl)(unsafe.Pointer(v.RawVTable))
}
