// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package controls

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureVariableSizedWrapGrid string = "rc(Windows.UI.Xaml.Controls.VariableSizedWrapGrid;{9ca507c7-23c9-4f01-b80f-be5c21eef474})"

type VariableSizedWrapGrid struct {
	ole.IUnknown
}

func NewVariableSizedWrapGrid() (*VariableSizedWrapGrid, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Xaml.Controls.VariableSizedWrapGrid")
	if err != nil {
		return nil, err
	}
	return (*VariableSizedWrapGrid)(unsafe.Pointer(inspectable)), nil
}

func (impl *VariableSizedWrapGrid) SetItemHeight(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiVariableSizedWrapGrid))
	defer itf.Release()
	v := (*iVariableSizedWrapGrid)(unsafe.Pointer(itf))
	return v.SetItemHeight(value)
}

func (impl *VariableSizedWrapGrid) SetItemWidth(value float64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiVariableSizedWrapGrid))
	defer itf.Release()
	v := (*iVariableSizedWrapGrid)(unsafe.Pointer(itf))
	return v.SetItemWidth(value)
}

func (impl *VariableSizedWrapGrid) SetOrientation(value Orientation) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiVariableSizedWrapGrid))
	defer itf.Release()
	v := (*iVariableSizedWrapGrid)(unsafe.Pointer(itf))
	return v.SetOrientation(value)
}

func (impl *VariableSizedWrapGrid) SetMaximumRowsOrColumns(value int32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiVariableSizedWrapGrid))
	defer itf.Release()
	v := (*iVariableSizedWrapGrid)(unsafe.Pointer(itf))
	return v.SetMaximumRowsOrColumns(value)
}

const GUIDiVariableSizedWrapGrid string = "9ca507c7-23c9-4f01-b80f-be5c21eef474"
const SignatureiVariableSizedWrapGrid string = "{9ca507c7-23c9-4f01-b80f-be5c21eef474}"

type iVariableSizedWrapGrid struct {
	ole.IInspectable
}

type iVariableSizedWrapGridVtbl struct {
	ole.IInspectableVtbl

	GetItemHeight                  uintptr
	SetItemHeight                  uintptr
	GetItemWidth                   uintptr
	SetItemWidth                   uintptr
	GetOrientation                 uintptr
	SetOrientation                 uintptr
	GetHorizontalChildrenAlignment uintptr
	SetHorizontalChildrenAlignment uintptr
	GetVerticalChildrenAlignment   uintptr
	SetVerticalChildrenAlignment   uintptr
	GetMaximumRowsOrColumns        uintptr
	SetMaximumRowsOrColumns        uintptr
}

func (v *iVariableSizedWrapGrid) VTable() *iVariableSizedWrapGridVtbl {
	return (*iVariableSizedWrapGridVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iVariableSizedWrapGrid) SetItemHeight(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetItemHeight,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iVariableSizedWrapGrid) SetItemWidth(value float64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetItemWidth,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in float64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iVariableSizedWrapGrid) SetOrientation(value Orientation) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOrientation,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in Orientation
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iVariableSizedWrapGrid) SetMaximumRowsOrColumns(value int32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMaximumRowsOrColumns,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in int32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
